antvis/L7

demos/08_arc_line.html, demos/great_circle.html, demos/patternline.html, demos/pointshape.html, package.json, src/core/image.js, src/core/layer.js, src/core/scene.js, src/geom/material/lineMaterial.js, src/geom/shader/arcline_frag.glsl, src/geom/shader/arcline_vert.glsl, src/geom/shader/circle_frag.glsl, src/geom/shader/great_circle_line_vert.glsl, src/geom/shader/meshline_frag.glsl, src/layer/render/line/drawArc.js, src/layer/render/line/drawMeshLine.js
=> fix(point): 修复shape映射,图片加载的事件

demos/01_circle.html, demos/01_point_circle.html, src/core/layer.js
=> 修复 removelayer 清除交互事件的bug

README.md, package.json, src/component/marker.js, src/map/AMap.js
=> update readme 

src/core/controller/event.js, src/core/engine/picking/picking.js, src/core/layer.js, src/core/scene.js
=> fix(event): add touch event

demos/01_point_circle.html, demos/line.html, demos/marker.html, demos/world.html, package.json, src/component/control/attribution.js, src/component/css/l7.css, src/component/marker.js, src/component/popup.js, src/core/engine/composer.js, src/core/engine/index.js, src/core/engine/picking/picking.js, src/core/scene.js, src/core/style.js, src/geom/material/lineMaterial.js, src/geom/material/material.js, src/geom/material/pointMaterial.js, src/geom/shader/great_circle_line_vert.glsl, src/layer/render/line/drawArc.js, src/layer/render/text/drawText.js, src/map/AMap.js, src/theme/blank.js, src/theme/index.js, src/worker/actor.js
=> 修复优化地图的一些方法

src/component/css/l7.css, src/geom/buffer/point/text.js, src/layer/render/text/drawText.js, src/map/AMap.js
新增文本避让开关方法
style({
textAllowOverlap: true
})
=> feat(text): text add textAllowOverlap propertry fix #34

demos/china.html, demos/dashline.html, demos/icon.html, package.json, src/core/engine/picking/picking.js, src/core/scene.js, src/geom/buffer/point/image_buffer.js, src/geom/extrude.js, src/geom/material/pointMaterial.js, src/geom/shader/point_frag.glsl, src/geom/shader/point_vert.glsl, src/layer/render/line/drawMeshLine.js, src/layer/render/point/drawImage.js, src/layer/render/point/drawNormal.js, src/util/throttle.js
=> point layer iamge

package-lock.json, package.json, packages/core/src/index.ts, packages/core/src/services/asset/IIconService.ts, packages/core/src/services/asset/IconService.ts, packages/core/src/services/layer/ILayerService.ts, packages/core/src/services/map/IMapService.ts, packages/core/src/services/scene/ISceneService.ts, packages/core/src/services/scene/SceneService.ts, packages/layers/package.json, packages/layers/src/heatmap/index.ts, packages/layers/src/line/index.ts, packages/layers/src/plugins/DataSourcePlugin.ts, packages/layers/src/point/point.ts, packages/maps/package.json, packages/maps/src/amap/index.ts, packages/maps/src/mapbox/index.ts, packages/maps/typings/index.d.ts, packages/scene/src/index.ts, packages/source/package.json, packages/source/src/parser/csv.ts, packages/source/src/parser/json.ts, stories/MapAdaptor/components/Polygon.tsx, tsconfig.json, yarn.lock
=> feat(core): add map method

gatsby-config.js, package.json
=> 🚀 l7.antv.vision

babel.config.js, package.json, packages/l7/es/index.js, packages/l7/es/index.js.map
=> fix(babel): gatsby env

.travis.yml, .yarnrc, README.md, README.zh.md, babel.config.js, docs/api/l7.en.md, docs/api/l7.zh.md, package.json, packages/renderer/src/regl/__tests__/model.spec.ts
=> test: improve travis ci

site/locale.json, site/pages/index.zh.tsx
=> Update home page slogan

docs/api/l7.zh.md, docs/api/l7stable.en.md, docs/api/l7stable.zh.md, docs/api/scene.en.md, docs/api/scene.zh.md, docs/tutorial/map/amap.en.md, docs/tutorial/map/amap.zh.md, docs/tutorial/map/mapbox.en.md, docs/tutorial/map/mapbox.zh.md, docs/tutorial/quickstart.en.md, gatsby-config.js
=> docs(docs): add 1.x 版本的介绍

docs/api/component/control.zh.md, docs/api/component/marker.en.md, docs/api/scene.en.md, docs/api/scene.zh.md, docs/tutorial/quickstart.en.md, docs/tutorial/quickstart.zh.md
=> docs(api): update setMapStyle API fix:#98

docs/api/layer/layer.en.md, docs/api/layer/layer.zh.md, docs/tutorial/map/mapbox.zh.md, docs/tutorial/quickstart.en.md, docs/tutorial/quickstart.zh.md, examples/point/chart/demo/bar.js, examples/point/chart/demo/chart.js, examples/point/chart/demo/ring.js, examples/point/marker/demo/marker.js, examples/tutorial/marker/demo/amap.js, packages/component/package.json, packages/core/package.json, packages/core/src/services/component/MarkerService.ts, packages/l7/package.json, packages/layers/package.json, packages/maps/package.json, packages/renderer/package.json, packages/scene/package.json, packages/source/package.json, packages/utils/package.json, stories/Components/components/Marker.tsx, stories/Components/components/Popup.tsx, stories/Components/components/Scale.tsx, stories/Components/components/Zoom.tsx
=> Fix(component): marker

docs/tutorial/map/amap.en.md, docs/tutorial/map/amap.zh.md, docs/tutorial/map/mapbox.en.md, docs/tutorial/map/mapbox.zh.md, docs/tutorial/quickstart.en.md, docs/tutorial/quickstart.zh.md, packages/layers/src/point/shaders/extrude_vert.glsl
=> docs(docs): fix docs error

docs/tutorial/map/amap.en.md, docs/tutorial/map/amap.zh.md, docs/tutorial/map/mapbox.en.md, docs/tutorial/map/mapbox.zh.md, docs/tutorial/quickstart.en.md, docs/tutorial/quickstart.zh.md
=> docs(docs): update 2.x version

.storybook/webpack.config.js, packages/component/src/control/BaseControl.ts, packages/core/src/shaders/projection.glsl, packages/maps/src/amap/index.ts, stories/Layers/Layers.stories.tsx, stories/Layers/components/column.tsx
=> fix(map): temporarily closed  amap offset coordinate

docs/api/l7stable.en.md, docs/api/l7stable.zh.md, docs/tutorial/map/amap.en.md, docs/tutorial/map/amap.zh.md, docs/tutorial/map/mapbox.en.md, docs/tutorial/map/mapbox.zh.md, docs/tutorial/quickstart.en.md, docs/tutorial/quickstart.zh.md, gatsby-config.js
=> chore(version): update docs demo version

babel.config.js, package.json, yarn.lock
fix #112
* 根据 `browserslist` 编译
* 添加 `core-js`
=> build(babel): transpile according to browserslist, add `core-js`

docs/tutorial/map/amap.en.md, docs/tutorial/map/amap.zh.md, docs/tutorial/map/blankmap.en.md, docs/tutorial/map/mapbox.en.md, docs/tutorial/map/mapbox.zh.md, docs/tutorial/quickstart.en.md, docs/tutorial/quickstart.zh.md
=> docs: update l7 cdn version

packages/maps/src/mapbox/index.ts
修复如果用户传递的是基于 mapboxgl 封装后的对象，一些参数的判断问题。
=> fix(mapbox): 针对传递 mapInstance 时，一些参数判断问题。

site/pages/index.zh.tsx
=> docs: fix home page unexpected scrollbar

docs/api/component/marker.zh.md, docs/api/layer/line_layer/linelayer.zh.md, examples/gallery/basic/demo/animate.js, examples/gallery/basic/demo/build.js, examples/gallery/basic/demo/meta.json, examples/line/path/demo/meta.json, examples/line/path/demo/road_dark_dash.js, examples/raster/basic/demo/dem.js, examples/raster/basic/demo/light.js, examples/raster/basic/demo/meta.json, examples/raster/basic/demo/ndvi.js, packages/component/src/css/l7.css, packages/component/src/marker.ts, packages/core/src/services/scene/ISceneService.ts, packages/core/src/services/scene/SceneService.ts, packages/layers/src/citybuliding/shaders/build_frag.glsl, packages/layers/src/core/BaseLayer.ts, packages/layers/src/line/shaders/line_frag.glsl, packages/scene/src/index.ts, stories/Components/components/Marker.tsx
=> feat: marker 支持鼠标事件

docs/api/layer/layer.zh.md, docs/tutorial/demo.zh.md, docs/tutorial/interactive/hightlight.zh.md, docs/tutorial/map/offline.en.md, docs/tutorial/map/offline.zh.md
=> docs: 增加图层高亮教程

README.zh-CN.md, docs/api/component/marker.en.md, docs/api/component/marker.zh.md, docs/api/component/markerLayer.en.md, docs/api/component/markerLayer.zh.md, docs/api/layer/point_layer/marker.en.md, docs/api/layer/point_layer/marker.zh.md, examples/point/marker/demo/clustermarker.js, examples/point/marker/demo/marker.js, examples/point/marker/demo/markerlayer.js, examples/point/marker/demo/meta.json, packages/component/src/css/l7.css, packages/component/src/index.ts, packages/component/src/markerlayer.ts, packages/core/src/services/component/IMarkerService.ts, packages/core/src/services/component/MarkerService.ts, packages/core/src/services/log/LogService.ts, packages/core/src/services/scene/SceneService.ts, packages/scene/src/index.ts, site/css/demo.css, stories/Components/Components.stories.tsx, stories/Components/components/clusterMarker.tsx, stories/Components/components/markerlayer.tsx
=> feat(component): 新增cluster marker

docs/api/component/marker.zh.md, docs/api/component/popup.en.md, docs/api/component/popup.zh.md, docs/api/layer/layer.en.md, docs/api/layer/layer.zh.md
=> docs: update layer docs

docs/api/component/markerLayer.en.md, docs/api/component/popup.en.md, docs/api/component/popup.zh.md, packages/component/src/popup.ts
=> feat: popup add open event

packages/core/src/shaders/picking.frag.glsl, stories/Source/Map.stories.tsx, stories/Source/components/updatedata.tsx
=> fix: hightlight opacity

packages/layers/src/point/models/text.ts, packages/source/src/source.ts, packages/source/src/transform/hexagon.ts, packages/source/src/transform/join.ts, stories/Layers/components/Text.tsx
=> fix: text overlap

docs/api/component/markerLayer.zh.md, packages/component/src/control/BaseControl.ts, packages/component/src/control/layer.ts, packages/component/src/control/logo.ts, packages/component/src/control/scale.ts, packages/component/src/control/zoom.ts, packages/component/src/markerlayer.ts, packages/core/src/services/component/ControlService.ts, packages/core/src/services/component/IControlService.ts, packages/core/src/services/layer/LayerService.ts, packages/core/src/services/renderer/IMultiPassRenderer.ts, packages/core/src/services/renderer/passes/MultiPassRenderer.ts, packages/core/src/services/renderer/passes/PixelPickingPass.ts, packages/core/src/services/scene/SceneService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/point/models/text.ts, packages/scene/src/index.ts, stories/Components/components/clusterMarker.tsx
=> Layer async

.travis.yml, docs/api/component/marker.en.md, docs/api/component/marker.zh.md, docs/api/source/source.en.md, docs/api/source/source.zh.md, package.json, packages/component/src/marker.ts, packages/core/src/services/layer/IStyleAttributeService.ts, packages/core/src/services/layer/StyleAttribute.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/DataMappingPlugin.ts, packages/layers/src/plugins/FeatureScalePlugin.ts, packages/layers/src/point/shaders/image_vert.glsl, packages/source/src/transform/join.ts, stories/Components/components/Marker.tsx, stories/Layers/components/Line.tsx, stories/Layers/components/Point3D.tsx, stories/Layers/components/PointImage.tsx
=> fix: many bugs

packages/react/src/component/Layer.ts, packages/react/src/component/LayerAttribute/Active.tsx, packages/react/src/component/LayerAttribute/Color.tsx, packages/react/src/component/LayerAttribute/Filter.tsx, packages/react/src/component/LayerAttribute/Layer.tsx, packages/react/src/component/LayerAttribute/Shape.tsx, packages/react/src/component/LayerAttribute/Size.tsx, packages/react/src/component/LayerAttribute/Source.tsx, packages/react/src/component/LayerAttribute/index.ts, packages/react/src/component/LayerContext.tsx, packages/react/src/component/LayerEvent.tsx, packages/react/src/component/Scene.tsx, packages/react/src/component/SceneContext.tsx, packages/react/src/index.ts
=> 优化React封装，新增组件

packages/core/src/shaders/projection.glsl, stories/Layers/components/Point3D.tsx, stories/Layers/components/PointImage.tsx
=> fix: mapbox 3d 柱图显示问题

packages/react/src/component/LayerAttribute/Layer.tsx, packages/react/src/component/LayerEvent.tsx, packages/react/src/component/Scene.tsx, packages/react/src/component/SceneEvent.tsx
修复以下问题：
* Scene组件传参错误；
* 事件传参错误；
* autoFit不生效；
=> 修复l7-react中的几个小问题

.github/CONTRIBUTING.md, packages/core/src/services/map/IMapService.ts, packages/core/src/services/renderer/passes/BasePostProcessingPass.ts, packages/core/src/utils/math.ts, packages/layers/src/utils/polylineNormal.ts, packages/maps/src/mapbox/map.ts, packages/react/src/component/AMapScene.tsx, packages/react/src/component/LayerAttribute/Layer.tsx, packages/react/src/component/LayerContext.tsx, packages/react/src/component/MapboxScene.tsx, packages/react/src/component/Popup.tsx, packages/react/src/component/Scene.tsx, packages/react/src/component/SceneContext.tsx, packages/renderer/src/regl/__tests__/model.spec.ts, packages/renderer/src/regl/__tests__/model.uniform.spec.ts, packages/scene/src/index.ts, yarn.lock
=> refactor: tslint error

packages/react/src/component/AMapScene.tsx, packages/react/src/component/MapboxScene.tsx, packages/react/src/component/Scene.tsx, packages/react/src/component/SceneContext.tsx
=> fix: 修复MapboxScene的容器找不到

packages/core/src/services/scene/ISceneService.ts, packages/core/src/services/scene/SceneService.ts, packages/core/src/utils/dom.ts, packages/maps/src/amap/map.ts, packages/react/src/component/LayerAttribute/Source.tsx, packages/react/src/component/LayerAttribute/index.ts, stories/Layers/components/column.tsx, stories/Layers/components/polygon_line.tsx
=> fix: 高德地图logo & scene 为初始化完成销毁 & 地图背景问题

packages/maps/package.json, packages/maps/typings/index.d.ts, packages/react/src/component/Scene.tsx
=> fix: fix map reference

examples/react/covid/demo/covid_bubble.tsx, lerna.json, packages/component/package.json, packages/core/package.json, packages/core/src/services/interaction/InteractionService.ts, packages/l7/demo/polygon.html, packages/l7/package.json, packages/layers/package.json, packages/maps/package.json, packages/react/package.json, packages/renderer/package.json, packages/scene/package.json, packages/source/package.json, site/pages/index.zh.tsx
=> Ios 12 event

packages/core/src/services/interaction/InteractionService.ts
=> fix: ios touchstart && double touch

packages/core/src/services/interaction/PickingService.ts, stories/Draw/Components/DrawCircle.tsx, stories/React/components/world.tsx
=> fix: picking

packages/component/src/control/zoom.ts, packages/layers/src/citybuliding/models/build.ts, packages/layers/src/line/models/arc.ts, packages/layers/src/line/models/arc_3d.ts, packages/layers/src/line/models/great_circle.ts, packages/layers/src/plugins/DataMappingPlugin.ts, packages/layers/src/plugins/RegisterStyleAttributePlugin.ts, packages/layers/src/plugins/UpdateModelPlugin.ts, packages/layers/src/point/models/fill.ts, packages/layers/src/point/models/image.ts, packages/layers/src/point/models/normal.ts, packages/layers/src/point/models/text.ts, packages/layers/src/polygon/models/extrude.ts, packages/source/src/parser/json.ts, stories/Layers/components/Arcline.tsx
=> fix: 修复文本更新bug fixes #232

packages/layers/src/heatmap/index.ts, packages/layers/src/heatmap/models/heatmap.ts, packages/layers/src/heatmap/shaders/heatmap_3d_frag.glsl, packages/layers/src/heatmap/shaders/heatmap_frag.glsl, packages/layers/src/heatmap/shaders/heatmap_framebuffer_frag.glsl, packages/layers/src/heatmap/shaders/heatmap_framebuffer_vert.glsl, packages/layers/src/heatmap/shaders/heatmap_vert.glsl, packages/layers/src/point/shaders/image_frag.glsl, packages/layers/src/raster/models/raster.ts, packages/layers/src/raster/raster.ts, packages/layers/src/raster/raster2d.ts, packages/layers/src/raster/shaders/raster_2d_frag.glsl, packages/layers/src/raster/shaders/raster_vert.glsl, packages/utils/src/color.ts, stories/Layers/Layers.stories.tsx, stories/Layers/components/HeatMap.tsx, stories/Layers/components/heatmap3d.tsx
=> fix: 修复颜色纹理取色问题 & 图片标注默认颜色问题

CHANGELOG.md, packages/core/src/services/config/ConfigService.ts, packages/core/src/services/config/IConfigService.ts, packages/core/src/services/interaction/IPickingService.ts, packages/core/src/services/interaction/PickingService.ts, packages/core/src/services/scene/SceneService.ts, packages/l7/src/version.ts, stories/Layers/components/Point.tsx
=> fix: 低端移动设备拾取画布太大内存泄漏的问题

.github/workflows/gitleaks.yml, .gitleaks.toml, .travis.yml
=> chore: add gitleaks

packages/layers/src/line/shaders/line_arc_frag.glsl
=> fix: animate shader bug

packages/draw/src/draw_control.ts, stories/Draw/Components/Circle.tsx, stories/Draw/Components/DrawControl.tsx
=> fix(draw): draw control event

packages/draw/src/modes/draw_feature.ts, packages/draw/src/modes/draw_mode.ts
=> fix(draw): fix draw rect bug

packages/district/src/layer/baseLayer.ts, packages/district/src/layer/country.ts, packages/district/src/layer/drillDown.ts, packages/district/src/layer/interface.ts, packages/district/src/layer/world.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/FeatureScalePlugin.ts, stories/District/Layer/Country.tsx, stories/Layers/components/polygon.tsx
=> fix(district): fix polygon layer setData 样式不生效 & 增加下钻上取地图

examples/district/basic/demo/china_map.js, gatsby-browser.js, package.json, packages/renderer/src/regl/__tests__/model.uniform.spec.ts, yarn.lock
=> docs: fix duplicated antd css

gatsby-browser.js
用 less，可以共享主题变量，避免侧边 Menu 被覆盖为蓝色的问题。
=> style: import antd less

examples/district/basic/API.zh.md, examples/district/drill/demo/meta.json, packages/district/src/config_1.ts, packages/district/src/index.ts, packages/district/src/layer/baseLayer.ts, packages/district/src/layer/country.ts, packages/district/src/layer/province.ts, packages/district/src/layer/world.ts, stories/District/district.stories.tsx
=> refactor(district): 对行政区划进行抽稀处理

package.json, stories/District/Layer/drillDown.tsx, stories/District/district.stories.tsx, yarn.lock
=> fix(storybook): 移除使用antd的demo,解决storybook ts 编译报错问题

docs/api/layer/layer.en.md, docs/api/layer/layer.zh.md, package.json, packages/district/src/config_1.ts, packages/district/src/index.ts, packages/district/src/layer/baseLayer.ts, packages/district/src/layer/country.ts, packages/district/src/layer/province.ts, packages/district/src/layer/world.ts, packages/maps/package.json, stories/Components/components/Zoom.tsx, yarn.lock
=> fix(district): 边界不契合的问题

examples/heatmap/grid/demo/grid_world.js, examples/heatmap/grid/demo/meta.json, examples/heatmap/hexagon/demo/china.js, packages/district/src/config.ts, packages/district/src/index.ts, packages/district/src/layer/baseLayer.ts, packages/district/src/layer/city.ts, packages/district/src/layer/country.ts, packages/district/src/layer/interface.ts, packages/district/src/layer/province.ts, packages/district/src/layer/world.ts, packages/utils/__tests__/statistic.spec.ts, packages/utils/src/statistics.ts, stories/District/Layer/world.tsx, stories/Layers/components/hexagon.tsx
=> fix(layer): fix sum statistic

packages/component/src/markerlayer.ts
在 MarkerLayer.clear() 中 clusterMarkers 没有被移除
=> fix(component): remove all markers from clusterMarkers in MarkerLayer.clear()

packages/boundry/src/config.ts, packages/boundry/src/layer/country.ts, packages/component/src/popup.ts, packages/draw/src/modes/draw_feature.ts, packages/draw/src/modes/draw_line.ts, packages/draw/src/modes/draw_point.ts, packages/draw/src/modes/draw_polygon.ts, packages/layers/src/line/models/arc.ts, packages/layers/src/line/models/arc_3d.ts, packages/layers/src/line/models/great_circle.ts, packages/layers/src/line/models/line.ts, packages/layers/src/line/shaders/line_arc2d_vert.glsl, packages/layers/src/line/shaders/line_arc_3d_vert.glsl, packages/layers/src/line/shaders/line_arc_frag.glsl, packages/layers/src/line/shaders/line_arc_great_circle_vert.glsl, packages/layers/src/line/shaders/line_arc_vert.glsl, packages/layers/src/line/shaders/line_bezier_vert.glsl, packages/layers/src/line/shaders/line_frag.glsl, packages/layers/src/line/shaders/line_vert.glsl, packages/maps/src/mapbox/map.ts, stories/District/Layer/country_city.tsx, stories/Draw/Components/DrawLine.tsx, stories/Draw/Components/DrawPoint.tsx, stories/Layers/components/Polygon3D.tsx, stories/Layers/components/dash.tsx, stories/Layers/components/polygon.tsx, stories/Source/components/multiPolygon.tsx
=> Fix draw line

packages/boundry/src/index.ts
=> fix(district): 区划接口定义导出

packages/layers/src/core/BaseLayer.ts, packages/source/src/source.ts, stories/District/Layer/world.tsx
=> fix(source & layer): setData update cfg

examples/react/layer/demo/world.jsx, packages/boundry/package.json, packages/boundry/src/config.ts, packages/boundry/src/layer/baseLayer.ts, packages/boundry/src/layer/interface.ts, packages/draw/src/draw_control.ts, packages/draw/src/modes/draw_feature.ts, packages/layers/src/plugins/FeatureScalePlugin.ts, packages/layers/src/point/__tests__/layer.spec.ts, packages/source/src/transform/join.ts, stories/District/Layer/world.tsx, stories/Layers/components/Point.tsx, tslint.test.json
=> fix(layer): 更新空数据& filter 方法

.github/CONTRIBUTING_ENGLISH.md
Convert CONTRIBUTING.md written to English in a new file called  CONTRIBUTING_ENGLISH.md
Part of issue #414
=> docs: Add english version of CONTRIBUTING.md

docs/api/district/baselayer.zh.md, examples/district/basic/API.zh.md, examples/district/basic/demo/attach_map.js, examples/district/basic/demo/hainan.js, examples/district/basic/demo/meta.json, examples/district/react/demo/province.tsx, packages/boundry/src/config.ts, packages/boundry/src/layer/drillDown.ts, packages/boundry/src/layer/interface.ts, stories/District/Layer/Country.tsx, stories/District/Layer/drillDown.tsx
=> chore(district): update china data

packages/source/src/source.ts
=> fix(source): 获取选中数据数据被修改的bug

packages/layers/src/point/models/image.ts
=> fix(layer): 图片图层重绘

packages/renderer/src/regl/ReglElements.ts
=> fix(render): fix elemet double destroy error

packages/core/src/services/layer/StyleAttributeService.ts, stories/Layers/components/polygon.tsx
=> fix(layer): 图层更新问题

docs/api/scene.en.md, docs/api/scene.zh.md
=> fix: update docs

packages/core/src/services/scene/SceneService.ts
=> fix: resize

packages/maps/src/mapbox/map.ts
=> fix(maps): mapbox drag rotate

packages/scene/src/index.ts
=> fix(scene): hasImage未返回有效值

packages/react/src/component/AMapScene.tsx
=> fix(react): 高德地图地图状态同步

packages/draw/src/modes/draw_circle.ts, packages/draw/src/util/constant.ts, packages/source/src/transform/grid.ts, stories/Layers/components/gridtest.tsx, stories/Layers/components/hexagon.tsx
=> feat(draw): draw circle add  change event

examples/line/path/demo/road_light.js, packages/layers/src/utils/__tests__/extrude_polyline.spec.ts, packages/layers/src/utils/extrude_polyline.ts
=> fix: 修复去除重复点计算逻辑的 bug

package.json, packages/boundary/src/layer/baseLayer.ts, packages/component/src/marker.ts, packages/component/src/popup.ts, packages/core/src/services/scene/ISceneService.ts, packages/core/src/services/scene/SceneService.ts, stories/District/Layer/country_bubble.tsx, yarn.lock
=> Fix issues 行政区划

babel.config.js, package.json, packages/core/src/services/scene/SceneService.ts, packages/maps/src/map/index.ts, packages/maps/src/map/map.ts, yarn.lock
=> fix: npm start error

packages/core/src/services/source/ISourceService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/DataSourcePlugin.ts, packages/source/__tests__/source.spec.ts, packages/source/src/source.ts, packages/utils/src/geo.ts
=> fix(layer): 解决PointLayer中配置了cluster:true缺少部分数据的问题

packages/core/src/services/interaction/InteractionService.ts, packages/l7/demo/polygon.html, packages/utils/src/color.ts
=> fix: 修复IE事件问题

packages/scene/src/index.ts
=> fix(scene): 地图panBy 方法

packages/core/src/services/interaction/IInteractionService.ts, packages/core/src/services/interaction/InteractionService.ts, packages/core/src/services/interaction/PickingService.ts, stories/Layers/components/polygon.tsx
=> feat(core): interaction

gatsby-node.js, packages/core/src/services/renderer/passes/MultiPassRenderer.ts, packages/core/src/services/renderer/passes/PostProcessor.ts, packages/core/src/services/renderer/passes/RenderPass.ts, tsconfig.json
暂时移除后处理模块，下钻场景下会多次触发 `fbo.resize`
#519
=> fix: 暂时去除后处理

.github/workflows/mirror.yml
gitee-pages-action breakchang
https://github.com/yanglbme/gitee-pages-action/issues/22
=> chore: config gitee mirror branch

docs/api/react/marker.zh.md
=> docs:  Update marker.zh.md

packages/maps/package.json
=> fix: loadstyle 依赖

docs/api/react/marker.zh.md, packages/core/src/services/asset/FontService.ts, packages/core/src/services/asset/IIconService.ts, packages/core/src/services/asset/IconService.ts, packages/core/src/utils/font_util.ts, packages/l7/src/version.ts, packages/layers/src/point/index.ts, packages/layers/src/point/models/image.ts, packages/layers/src/point/shaders/image_frag.glsl, stories/District/Layer/drillDown.tsx, stories/Layers/components/PointImage.tsx, stories/Layers/components/Text.tsx, stories/React/components/Scene.tsx
=> Fix font safari

docs/api/scene.zh.md
=> fix: eslint error

packages/utils/src/dom.ts
=> fix: getViewPortScale边界情况处理

packages/core/src/services/interaction/InteractionService.ts, packages/l7/src/version.ts, stories/Layers/components/PointImage.tsx
=> Fix mousedown

packages/component/src/marker.ts
修复当前代码存在的两个问题：
1. 高德地图下display为none的逻辑有问题，导致某些情况下可视区域内点消失
2. mapbox地图下可视区域包含日界线时，只能看到日界线一侧的点，另一侧点看不到
=> fix: 修复可视区域包含日界线时点不可见的问题;隐藏可视区域外打点

packages/layers/src/plugins/DataSourcePlugin.ts
=> fix: cluster 模式下，point 后续 setData，不会立即生效

docs/tutorial/quickstart.en.md, docs/tutorial/quickstart.zh.md
style: 'dark' is not work, use mapStyle instead.
根据 https://lbs.amap.com/api/javascript-api/reference/map/?sug_index=1 文档的配置项，修改官网文档示例 Demo 中的错误
=> docs: GaodeMap options style -> mapStyle

packages/source/src/source.ts
=> fix(cluster): pointLayer相同经纬度点不聚合

packages/layers/src/point/models/fill.ts, packages/layers/src/point/shaders/fill_vert.glsl
=> fix: 点图层设置

gatsby-config.js
=> feat: 取消 demo 案例 playground container 的 min-height: 500px，加上该样式会让地图容器上移

packages/component/src/control/BaseControl.ts, packages/maps/src/mapbox/map.ts
=> fix: change mapbox token

packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/DataSourcePlugin.ts, stories/Source/Map.stories.tsx, stories/Source/components/ReuseSource.tsx
Support multi layer reuse source
=> feat(l7-layers): reuse source for multi layer

packages/core/src/services/interaction/InteractionService.ts, packages/core/src/services/scene/ISceneService.ts, packages/scene/src/index.ts
=> feat(scene): add once event for scene

packages/core/src/shaders/styleMapping.glsl, packages/layers/src/core/BaseModel.ts
=> Shihui dev

examples/line/arc/demo/meta.json, examples/line/arc/demo/trip_arc_dark_linear.js
=> feat: 增加官网渐变弧线案例

packages/layers/src/line/models/arc.ts, packages/layers/src/line/models/arc_3d.ts, packages/layers/src/line/models/great_circle.ts, packages/layers/src/line/models/line.ts, packages/layers/src/point/models/extrude.ts, packages/layers/src/point/models/fill.ts, packages/layers/src/point/models/icon-font.ts, packages/layers/src/point/models/image.ts, packages/layers/src/point/models/normal.ts, packages/layers/src/point/models/text.ts, packages/layers/src/polygon/models/extrude.ts, packages/layers/src/polygon/models/fill.ts, stories/Map/components/amap2demo_textOffset.tsx, stories/customMap/components/Map.tsx
=> feat: 处理 dataTesture 未回收导致的bug

beta.sh, latest.sh, packages/layers/src/core/BaseLayer.ts, packages/layers/src/core/BaseModel.ts, packages/layers/src/line/models/arc.ts, packages/layers/src/line/models/arc_3d.ts, packages/layers/src/line/models/great_circle.ts, packages/layers/src/line/models/line.ts, packages/layers/src/point/models/extrude.ts, packages/layers/src/point/models/fill.ts, packages/layers/src/point/models/image.ts, packages/layers/src/point/models/normal.ts, packages/layers/src/point/models/text.ts, packages/layers/src/polygon/models/extrude.ts, packages/layers/src/polygon/models/fill.ts, stories/Map/components/amap2demo_image.tsx, stories/Map/components/amap2demo_lineLinear.tsx
=> fix: 修复引入数据纹理导致的一些bug

babel.config.js, package.json
=> Fix site 2

packages/layers/src/point/models/image.ts, stories/Map/components/amap2demo_image.tsx
=> feat: 调整 icon 纹理绘制参数

packages/layers/src/core/triangulation.ts, packages/layers/src/point/models/extrude.ts, packages/layers/src/point/models/text.ts, packages/layers/src/utils/geo.ts
=> fix: fixed a naming typo

packages/component/src/popup.ts
=> fix(popup): 修改使用amap2.0时,popup不随地图联动的问题

docs/api/component/control.en.md, docs/api/component/control.zh.md, docs/api/draw/draw_control.zh.md, docs/api/react/scene.en.md, docs/api/react/scene.zh.md, docs/api/scene.en.md, docs/api/scene.zh.md
=> feat: 更新Control position 文档

package.json, site/components/rumbling/index.tsx, site/pages/map.zh.tsx, stories/Scale/Scale.stories.tsx, stories/Scale/components/Point.tsx
=> fix: 解决方案页面懒加载

docs/api/layer/heatmap_layer/grid.en.md, docs/api/layer/heatmap_layer/grid.zh.md, docs/api/layer/heatmap_layer/hexagon.en.md, docs/api/layer/heatmap_layer/hexagon.zh.md, docs/api/layer/heatmap_layer/normal.zh.md
=> docs: fix typo

docs/api/layer/layer.zh.md, docs/common/layer/layer_encode.md
=> docs: fix 404 links

docs/api/cityBuilding/cityBuilding.zh.md
=> docs: `CityBuildingLayer` doc

docs/api/earth/earth.zh.md
=> docs: 地球 `rotateY` 参数

docs/api/cityBuilding/cityBuilding.zh.md, docs/api/earth/earth.zh.md, docs/api/earth/flyline.zh.md, docs/api/earth/point.zh.md, docs/api/raster/raster_layer.zh.md
=> docs: 文档图片居中

docs/api/polygon_layer/polygonlayer.zh.md
=> docs: `PolygonLayer` doc

docs/api/earth/earth.zh.md, docs/api/earth/flyline.zh.md, docs/api/earth/point.zh.md
=> docs: 地球模式文档

docs/common/layer/layer_interaction.md, docs/tutorial/interactive/hightlight.zh.md, examples/react/covid/demo/covid_animate.tsx, examples/react/covid/demo/covid_bubble.tsx, examples/react/covid/demo/covid_column.tsx, examples/react/covid/demo/covid_extrude.tsx, examples/react/covid/demo/covid_fill.tsx, examples/react/covid/demo/covid_grid.tsx, examples/react/layer/API.en.md
=> docs: 更新 mix 例子

docs/api/polygon_layer/fill.zh.md, examples/line/path/demo/meta.json, examples/line/path/demo/turin.js
=> docs: 新增都灵线路图

examples/gallery/animate/demo/turin.js
=> docs: 更换主题色

examples/choropleth/administrative/demo/china-city.ts, examples/choropleth/administrative/demo/hangzhou-city.ts, examples/choropleth/administrative/demo/world-map.ts, examples/choropleth/administrative/demo/xihu-district.ts, examples/choropleth/administrative/demo/zhejiang-province-district.ts, examples/choropleth/administrative/demo/zhejiang-province.ts, examples/choropleth/drill/demo/drill-callback.ts, examples/choropleth/drill/demo/drill-intercept.ts, examples/choropleth/drill/demo/order-drill.ts, examples/choropleth/drill/demo/unorder-drill.ts, packages/scene/src/index.ts
=> docs(distict): demo of district

docs/api/point_layer/marker.zh.md
=> docs: fix wrong layer

stories/MapPerformance/components/DataUpdate.tsx, stories/MapPerformance/map.stories.tsx
=> chore(test demo): lineLayer date update

docs/api/district/start.zh.md, docs/common/district/choropleth.zh.md
=> docs: district guide

packages/layers/src/point/shaders/extrude/extrude_vert.glsl, stories/Map/components/amap2demo_extrude.tsx
=> fix: 修复 cylinder 在 mapbox 高度错误且 heightfixed 失效

docs/tutorial/map/blankmap.zh.md
=> docs: correct a handwriting error

packages/core/src/services/interaction/IPickingService.ts, packages/core/src/services/interaction/PickingService.ts, packages/core/src/services/scene/SceneService.ts, packages/layers/src/utils/symbol-layout.ts, packages/map/src/map.ts, packages/maps/src/amap2/map.ts, packages/maps/src/map/map.ts, packages/renderer/src/regl/index.ts, stories/Map/components/amap2demo_iconfont.tsx, stories/Map/components/bugfix.tsx
=> Changemarker

docs/api/scene.zh.md
=> change:修改代码错别字

packages/scene/src/index.ts, stories/Map/components/mask.tsx
=> fix: 修复 使用过mask 没有设置 maskfence 导致的问题

packages/maps/src/amap/theme.ts, packages/maps/src/amap2/theme.ts
=> chore: 兼容高德地图 V2 矢量瓦片样式

packages/component/src/markerlayer.ts, stories/Map/components/bugfix.tsx
=> fix MarkerLayer addMarker not update

packages/core/src/shaders/picking.frag.glsl, packages/layers/src/core/interface.ts, packages/layers/src/point/models/fill.ts, packages/layers/src/point/shaders/animate/wave_frag.glsl, packages/layers/src/point/shaders/extrude/extrude_frag.glsl, packages/layers/src/point/shaders/fill_frag.glsl, packages/layers/src/polygon/shaders/extrude/polygon_extrude_picklight_frag.glsl, stories/Map/components/amap2demo_styleMap.tsx, stories/Map/components/mapCenter.tsx
=> 为点图层补充 blur 配置

packages/layers/src/core/interface.ts, packages/layers/src/line/models/line.ts, packages/layers/src/line/shaders/line_vert.glsl, stories/Object/components/arrow.tsx
=> 增加线图层在配置箭头的时候支持配置线尾部宽度

packages/layers/src/line/models/wall.ts, packages/layers/src/line/shaders/dash/line_dash_vert.glsl
=> fix: 修复虚线失效

packages/l7/README.en-US.md, packages/l7/README.md
=> docs: update l7 package readme.md

packages/core/src/services/layer/IStyleAttributeService.ts, packages/layers/src/Geometry/shaders/sprite_frag.glsl, packages/layers/src/Geometry/shaders/sprite_vert.glsl, packages/layers/src/plugins/FeatureScalePlugin.ts, stories/Object/components/sprite.tsx
=> feat: sprite 优化，取消拾取，允许不设置 source

packages/core/src/services/interaction/PickingService.ts
=> fix: 修复 mouseup 失效

packages/core/src/services/interaction/PickingService.ts
=> feat: 优化代码，使用 Array.includes 代替 ||

packages/core/src/services/source/ISourceService.ts, packages/layers/package.json
=> fix: 补全 ISource 接口定义

docs/common/layer/mouse_event.md, packages/core/src/services/layer/ILayerService.ts, packages/layers/src/core/BaseLayer.ts
=> fix: 图层事件添加事件类型定义

packages/layers/package.json
=> fix: 修复 layer 包入口文件依赖注入有副作用影响

packages/layers/src/plugins/DataMappingPlugin.ts, packages/layers/src/plugins/ShaderUniformPlugin.ts
=> fix: 修复高德2 动态点位引发的 bug

packages/l7/src/version.ts, packages/layers/package.json
=> chore: 修改 d3-interpolate 类型定义依赖版本

packages/layers/src/plugins/DataMappingPlugin.ts, packages/layers/src/plugins/ShaderUniformPlugin.ts
=> feat: 高德2动态设置中心点

package.json
=> chore: 修改 lerna 版本号升级指令，l7 包内部固定依赖版本

packages/layers/src/line/models/arc.ts, packages/layers/src/line/models/arc_3d.ts, packages/layers/src/line/models/arcmini.ts, packages/layers/src/line/models/great_circle.ts, packages/layers/src/line/models/line.ts, packages/layers/src/line/models/linearline.ts, packages/layers/src/line/models/simpleLine.ts, packages/layers/src/line/models/wall.ts, packages/layers/src/point/models/extrude.ts, packages/layers/src/point/models/fill.ts, packages/layers/src/point/models/fillmage.ts, packages/layers/src/point/models/image.ts, packages/layers/src/point/models/normal.ts, packages/layers/src/point/models/radar.ts, packages/layers/src/point/models/simplePoint.ts, packages/layers/src/point/models/text.ts, packages/layers/src/polygon/models/extrude.ts, packages/layers/src/polygon/models/fill.ts, packages/layers/src/polygon/models/ocean.ts, packages/layers/src/polygon/models/water.ts, stories/Map/components/bugfix.tsx
=> fix： 修复样式数据映射失效

packages/core/src/services/interaction/InteractionService.ts, packages/core/src/services/interaction/PickingService.ts, packages/layers/src/polygon/models/extrude.ts, packages/layers/src/polygon/models/fill.ts
- 补全 hammerjs 事件监听的解除
- 在事件节流中排除 dblclick
- polygon 使用双面渲染
=> fix: 修复一些问题

packages/core/src/services/interaction/PickingService.ts
=> feat: 去除事件节流

packages/layers/src/tile/manager/tilePickerManager.ts, packages/layers/src/tile/tileFactory/base.ts, stories/tile/components/RasterArrayBuffer2.tsx, stories/tile/components/VectorPolygonTile.tsx
=> feat: 优化数据栅格的拾取

packages/layers/src/tile/tileFactory/base.ts, stories/tile/components/VectorPolygonTile.tsx, stories/tile/components/VectorProvinceAllTile.tsx
=> feat: 完善瓦片事件中 properties 的值透出

packages/component/src/css/l7.css, packages/component/src/index.ts, packages/component/src/markerlayer.ts
=> chore: 透出组件类型定义

stories/tile/components/RasterArrayBuffer.tsx, stories/tile/components/RasterArrayBuffer2.tsx, stories/tile/components/RasterTile.tsx, stories/tile/components/VectorPolygonTile.tsx, stories/tile/components/VectorProvince.tsx, stories/tile/components/VectorProvinceAllTile.tsx, stories/tile/components/lerc.tsx, stories/tile/components/timeline.tsx, stories/tile/map.stories.tsx
=> style: change demo

packages/layers/src/tile/tmsTileLayer.ts, packages/utils/src/tileset-manager/tileset-manager.ts, packages/utils/src/tileset-manager/utils/lonlat-tile.ts, stories/tile/components/QuXian.tsx, stories/tile/map.stories.tsx
瓦片支持从中心视野优先加载，通过离中心瓦片距离排序，越近的排在前面
=> feat: 瓦片支持从中心视野优先加载

packages/layers/src/tile/tileLayer/baseTileLayer.ts, packages/layers/src/tile/tmsTileLayer.ts, packages/utils/src/tileset-manager/const.ts, packages/utils/src/tileset-manager/tile.ts, packages/utils/src/tileset-manager/tileset-manager.ts, packages/utils/src/tileset-manager/utils/bound-buffer.ts, packages/utils/src/tileset-manager/utils/lonlat-tile.ts
- 瓦片加载添加缓冲区域
- 默认缓冲当前区域的 `0.2` 倍数区域
- 新增瓦片显示状态变更属性
- 修复数据服务 minZoom 情况
=> feat: 瓦片加载添加缓冲区域

packages/utils/src/tileset-manager/const.ts, packages/utils/src/tileset-manager/tileset-manager.ts, packages/utils/src/tileset-manager/types.ts, packages/utils/src/tileset-manager/utils/strategies.ts
- 新增瓦片实时更新策略
- 修改默认更新策略为 `替换更新`
=> feat: 新增瓦片实时更新策略

.storybook/preview.ts, examples/tile/raster/demo/dem.js, examples/tile/raster/demo/lerc.js, packages/core/src/services/layer/ILayerService.ts, packages/core/src/services/layer/LayerService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/core/interface.ts, packages/layers/src/raster/models/raster.ts, packages/layers/src/tile/manager/tileLayerManager.ts, packages/layers/src/tile/tileFactory/rasterData.ts, packages/layers/src/tile/tileLayer/baseTileLayer.ts, packages/layers/src/tile/tmsTileLayer.ts, stories/tile/components/demFilter.tsx, stories/tile/components/landCover.tsx
- 优化 tileUnload 时候的重复渲染
- 优化数据栅格 raster layer 色带贴图的重复构建
=> feat: 优化瓦片渲染性能

packages/renderer/src/regl/index.ts
=> fix: 修复 scene 销毁后重执行的 clear 导致的问题

README.en-US.md, README.md, docs/api/draw/start.zh.md, examples/draw/basic/index.en.md, gatsby-config.js, packages/l7/README.en-US.md, packages/l7/README.md
=> fix: L7Draw 对应 Github 和 文档地址变更

packages/layers/src/line/index.ts, packages/layers/src/line/models/half.ts, packages/layers/src/line/models/index.ts, packages/layers/src/line/shaders/half/line_half_frag.glsl, packages/layers/src/line/shaders/half/line_half_vert.glsl, packages/layers/src/plugins/DataMappingPlugin.ts, stories/Map/components/bugfix.tsx
https://www.yuque.com/docs/share/b9b91635-9a78-408c-9549-0eadfdfe4648?# 《带箭头线图层的单侧显示》
=> feat: add halfLine model

packages/layers/src/core/BaseLayer.ts, packages/layers/src/line/index.ts, packages/layers/src/line/models/earthArc_3d.ts, packages/layers/src/line/models/index.ts, packages/layers/src/point/index.ts, packages/layers/src/point/models/earthExtrude.ts, packages/layers/src/point/models/earthFill.ts, packages/layers/src/point/models/fill.ts, packages/layers/src/point/models/index.ts, packages/layers/src/point/shaders/earth/extrude_frag.glsl, packages/layers/src/point/shaders/earth/extrude_vert.glsl, packages/layers/src/point/shaders/earth/fill_frag.glsl, packages/layers/src/point/shaders/earth/fill_vert.glsl, stories/Map/components/bugfix.tsx, stories/customMap/components/earth.tsx, stories/customMap/components/earth2.tsx
=> feat: 去除 style 更新时 options 的更新、earth 图层解耦

.storybook/preview.ts, packages/maps/src/amap2/map.ts, packages/renderer/src/regl/index.ts, stories/Map/components/bugfix.tsx
=> fix: 修复 webgl context lost

build/rollup-plugin-inline-worker.js, packages/core/src/services/layer/StyleAttributeService.ts, packages/l7/src/worker.ts, packages/layers/src/core/triangulation.ts, packages/utils/src/worker-helper/index.ts
=> chore: 修改 worker 执行函数

build/rollup.config.worker.js, packages/l7/src/index.ts, packages/l7/src/worker.ts, packages/utils/package.json, packages/utils/src/worker-helper/index.ts, packages/utils/src/workers/index.ts
=> chore: worker 注册放到 utils 里面

.storybook/preview.ts, packages/layers/src/line/shaders/dash/arc_dash_frag.glsl, packages/layers/src/line/shaders/dash/line_dash_frag.glsl, packages/layers/src/line/shaders/line_arc_great_circle_frag.glsl
=> fix: fix dash line shader compile

packages/layers/src/wind/models/wind.ts, packages/layers/src/wind/models/windRender.ts, stories/Map/components/amap2demo_wind.tsx
https://www.yuque.com/antv/l7/lckqwp
=> feat: 优化风场图层的显示效果

packages/core/package.json, packages/renderer/package.json
=> chore: remove lib

dev-demos/features/point/image.md, dev-demos/features/point/image.tsx, dev-demos/features/point/tile.md, dev-demos/features/point/tile.tsx, packages/layers/src/core/interface.ts, packages/layers/src/image/models/image.ts, packages/renderer/package.json
=> feat: 优化图片的显示效果

dev-demos/features/point/linearline.md, dev-demos/features/point/linearline.tsx, packages/utils/src/color.ts
=> feat: 新增枚举类型的色带

packages/maps/src/amap/map.ts, packages/maps/src/amap2/map.ts
=> feat: 兼容 禁止多种API加载方式混用问题

packages/maps/src/amap/map.ts, packages/maps/src/amap2/map.ts
=> fix: 修复加载高德地图判断加载导致的缓存问题

dev-demos/features/tile/geojson-vt.md, dev-demos/features/tile/geojson-vt.tsx, dev-demos/features/tile/vectortile.tsx, packages/core/src/services/source/ISourceService.ts, packages/layers/src/line/index.ts, packages/layers/src/point/index.ts, packages/layers/src/polygon/index.ts, packages/layers/src/raster/index.ts, packages/layers/src/tile/manager/tileLayerManager.ts, packages/layers/src/tile/utils.ts, packages/source/package.json, packages/source/src/index.ts, packages/source/src/interface.ts, packages/source/src/parser/geojsonvt.ts, packages/source/src/parser/mvt.ts, packages/source/src/parser/raster-tile.ts, packages/source/src/source.ts
=> feat: 矢量图层支持 geojson-vt

dev-demos/features/heatmap/heatmap.md, dev-demos/features/heatmap/heatmap.tsx, packages/layers/src/heatmap/models/heatmap.ts
=> fix: heatmap render error

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/layers/src/tile/utils.ts, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.9.24 -> 2.9.25

dev-demos/features/customLayer/marker-layer.md, dev-demos/features/customLayer/marker.md, packages/component/__tests__/marker.spec.tsx
=> test: 新增marker组件测试用例，测试覆盖率0% -> 80%

packages/core/src/services/source/ISourceService.ts, packages/source/src/parser/geojson.ts, packages/source/src/parser/json.ts
=> feat: source 支持 json 下新增 geometry 字段

packages/component/src/marker-layer.ts
=> fix: 解决聚合情况下清空图层点数据未清空BUG

packages/layers/src/plugins/FeatureScalePlugin.ts, packages/source/src/source.ts
=> fix: 修复 feature scale 可能存在的 source 取值问题

dev-demos/features/tile/rastertile.tsx, packages/layers/src/image/models/image.ts, packages/layers/src/plugins/FeatureScalePlugin.ts
=> fix: 修复栅格图片瓦片的混合问题

.github/workflows/test.yml, .gitignore, jest.config.js, packages/layers/src/point/__tests__/layer_init.spec.ts, packages/renderer/src/regl/ReglElements.ts, packages/test-utils/src/create-context.ts, packages/test-utils/src/test-scene.ts, tsconfig.json, tslint.prod.json
=> chore: 增加覆盖率Ci

dev-demos/features/customLayer/marker-layer.md, packages/component/src/marker-layer.ts
=>  fix: 修复gaodev2下MarkerLayer清除有误问题

dev-demos/features/customLayer/marker-layer.md, packages/component/src/marker-layer.ts, packages/core/src/services/component/MarkerService.ts
Thank you for your pull request. Please review below requirements.
Bug fixes and new features should include tests and possibly benchmarks.
Contributors guide: https://github.com/antvis/L7/blob/master/.github/CONTRIBUTING.md
感谢您贡献代码。请确认下列 checklist 的完成情况。
Bug 修复和新功能必须包含测试，必要时请附上性能测试。
Contributors guide: https://github.com/antvis/L7/blob/master/.github/CONTRIBUTING.md 
- fix: #1320
=> fix: 自定义图层 - markerLayer - 修复图层执行clear后聚合能力失效问题 

.fatherrc.ts, .umirc.ts, packages/utils/.fatherrc.ts
迁移 father 打包时未迁移 worker 打包，添加开发与生产环境 worker 打包
=> build: worker 内联打包补加

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.9.32 -> 2.9.33

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: 更新版本 2.9.34

dev-demos/features/fix/demos/fix.tsx, packages/layers/src/core/BaseLayer.ts, packages/layers/src/utils/layerData.ts
=> fix: 优化多图层 setData 效果不同步的现象

dev-demos/features/tile/mask.md, dev-demos/features/tile/vector/mask.tsx, packages/layers/src/core/interface.ts, packages/layers/src/mask/index.ts, packages/layers/src/mask/models/index.ts, packages/layers/src/tile/tileFactory/base.ts, packages/layers/src/tile/tileFactory/index.ts, packages/layers/src/tile/tileFactory/mask.ts, packages/layers/src/tile/tileFactory/point.ts, packages/layers/src/tile/tileFactory/vectorLayer.ts
=> feat: 新增矢量瓦片类型 - 掩模图层

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.9.34 -> 2.9.35

dev-demos/features/fix/demos/fix2.tsx, dev-demos/features/fix/fix2.md, packages/layers/src/plugins/DataMappingPlugin.ts, packages/layers/src/plugins/ShaderUniformPlugin.ts, packages/maps/src/amap2/map.ts
=> fix: 修复设置地图中心点引发的问题

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.9.35 -> 2.9.36

packages/core/src/services/layer/ILayerService.ts, packages/layers/src/tile/manager/base.ts, packages/layers/src/tile/manager/layerManager.ts, packages/layers/src/tile/manager/mapLayerManager.ts, packages/layers/src/tile/tileLayer/base.ts, packages/utils/src/tileset-manager/tile.ts
=> feat: 瓦片更新代码重构

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.9.36 -> 2.9.37

dev-demos/features/rasterLayer/demos/rasterNDVI.tsx, dev-demos/features/rasterLayer/demos/rasterRgb3.tsx, dev-demos/features/rasterLayer/rasterNDVI.md, dev-demos/features/rasterLayer/rasterRgb3.md, dev-demos/features/tile/worldmap.md, dev-demos/features/tile/worldmap.tsx
=> chore: add bands demo

dev-demos/tile/district/simpleLine.tsx, dev-demos/tile/simpleLine.md, packages/core/src/services/layer/ILayerService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/core/triangulation.ts, packages/layers/src/line/index.ts, packages/layers/src/plugins/DataMappingPlugin.ts, packages/layers/src/point/__tests__/layer_init.spec.ts, packages/source/src/source.ts
=> feat: simple line 支持

dev-demos/tile/district/simpleLine.tsx, packages/core/src/services/layer/ILayerService.ts, packages/core/src/services/layer/LayerService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/tile/service/TileLayerService.ts, packages/layers/src/tile/tileFactory/Tile.ts, packages/layers/src/tile/tileFactory/VectorTile2.ts, packages/layers/src/tile/tileFactory/util.ts, packages/layers/src/utils/dataMappingStyle.ts
=> feat: add vector tile mask support

dev-demos/tile/district/image.tsx, dev-demos/tile/district/point.tsx, dev-demos/tile/point.md, packages/layers/src/tile/service/TileLayerService.ts, packages/layers/src/tile/tileFactory/MaskTile.ts, packages/layers/src/tile/tileFactory/index.ts, packages/layers/src/tile/tileFactory/util.ts, packages/scene/src/index.ts
=> feat: 增加 Mask Tile Layer

dev-demos/tile/district/imageRGB.tsx, dev-demos/tile/district/rasterData.tsx, dev-demos/tile/district/simpleLine.tsx, packages/core/src/services/interaction/PickingService.ts, packages/core/src/services/layer/ILayerService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/tile/interaction/utils.ts, packages/layers/src/tile/service/TileLayerService.ts, packages/layers/src/tile/service/TilePickService.ts, packages/layers/src/tile/style/style.ts, packages/layers/src/tile/tileFactory/RasterTile.ts, packages/layers/src/tile/tileFactory/Tile.ts, packages/layers/src/tile/tileLayer/BaseLayer.ts, packages/layers/src/tile/utils.ts
=> feat: Tile style update

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.10.0 -> 2.10.1

dev-demos/features/marker/demos/marker.tsx, dev-demos/features/marker/marker.md
=> docs: 添加marker demo

packages/layers/src/heatmap/models/heatmap.ts
=> fix: fix heatmap err

packages/layers/src/heatmap/models/heatmap.ts, packages/source/src/parser/geojsonvt.ts, packages/source/src/parser/testTile.ts
=> fix: 修复 heatmap 渲染失效

packages/layers/src/wind/models/wind.ts
=> fix: fix windLayer render failed

dev-demos/layer/control/exportImage.tsx, dev-demos/layer/control/hide.tsx, dev-demos/layer/control/layerSwitch.tsx, dev-demos/layer/control/mapTheme.tsx, dev-demos/layer/control/navigation.tsx, dev-demos/layer/control/remove.tsx, dev-demos/layer/control/setOptions.tsx, dev-demos/layer/popup/layerPopup.tsx, dev-demos/tile/district/polygon.tsx, dev-demos/tile/district/worldmap.tsx, packages/component/src/control/baseControl/popperControl.ts, packages/component/src/control/baseControl/selectControl.ts, packages/component/src/control/fullscreen.ts, packages/component/src/popup/layerPopup.ts, packages/component/src/popup/popup.ts, packages/core/src/services/interaction/IPickingService.ts, packages/core/src/services/interaction/PickingService.ts, packages/layers/src/tile/service/TileLayerService.ts, packages/layers/src/tile/service/TilePickService.ts, packages/layers/src/tile/tileFactory/Tile.ts, packages/layers/src/tile/tileFactory/VectorTile.ts, packages/source/src/parser/mvt.ts, packages/source/src/source.ts
1. 将瓦片数据的解析方法转移到 TIle 中，在使用的时候按需解析
2. 补全瓦片事件获取数据的方法 getFeatureById
=> feat: 瓦片图层事件获取数据、瓦片数据解析

package.json
=> fix: 修复 babel 升级导致的打包报错问题

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: 更新beta 版本

dev-demos/layer/control/position.tsx, packages/site/docs/api/polygon_layer/polygonlayer.zh.md
=> docs: 修正PolygonLayer图层shape属性文档中有歧义的数据映射描述

packages/layers/src/polygon/shaders/extrude/polygon_extrude_frag.glsl, packages/layers/src/polygon/shaders/extrude/polygon_extrude_picklight_frag.glsl, packages/layers/src/polygon/shaders/extrude/polygon_extrudetex_frag.glsl
=> fix: 修复部分机型 GPU 计算精度问题导致的polygonLayer渲染花纹出错问题

packages/component/src/control/baseControl/buttonControl.ts, packages/component/src/control/zoom.ts, packages/utils/src/index.ts
=> fix: 修复 Components 中引用 l7-utils 路径问题

packages/layers/src/tile/tileFactory/MaskTile.ts
=> fix: fix MaskTile failed

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: 升级版本

dev-demos/features/point/demos/simple.tsx, dev-demos/gallery/scale/quantile.tsx, dev-demos/gallery/scale/quantize.tsx, dev-demos/tile/Vector/demos/worldmap.tsx, package.json, packages/core/src/services/layer/ILayerService.ts, packages/core/src/services/layer/LayerService.ts, packages/core/src/services/scene/SceneService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/line/models/line.ts, packages/layers/src/plugins/DataMappingPlugin.ts, packages/maps/src/amap2/map.ts, packages/maps/src/utils/amap/AMapBaseService.ts, packages/site/.dumirc.ts, packages/site/examples/tile/vector/demo/simpleLine.ts, packages/site/examples/tile/vector/demo/worldmap.ts
=> fix: layer service clear

dev-demos/gallery/scale/quantile.tsx, lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: 版本号

packages/component/src/popup/layerPopup.ts, packages/component/src/popup/popup.ts, packages/site/docs/api/component/popup/popup.zh.md
=> fix: 修复 Popup 闭包问题

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: 更新版本 2.11.0

.github/CONTRIBUTING.md, .github/CONTRIBUTING_ENGLISH.md, README.en-US.md, README.md, packages/component/src/control/logo.ts, packages/l7/README.en-US.md, packages/l7/README.md, packages/site/.dumirc.ts, packages/site/docs/api/component/control/logo.zh.md, packages/site/docs/common/district/choropleth.zh.md, packages/site/package.json
=> docs: 更新 README 及新官网链接

lerna.json, packages/component/package.json, packages/component/src/control/logo.ts, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/docs/api/tile/geojsonvt_tile_layer.zh.md, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version v2.11.1 -> v2.11.2

dev-demos/features/tile/raster/satellite.tsx, dev-demos/features/tile/raster/signGenerator.ts, dev-demos/features/tile/rasterImage.md, package.json, packages/component/src/control/logo.ts, packages/core/src/services/source/ISourceService.ts, packages/layers/src/tile/tileFactory/index.ts, packages/site/docs/api/tile/geojsonvt_tile_layer.zh.md, packages/source/src/parser/raster-tile.ts, packages/source/src/utils/tile/getCustomData.ts, packages/source/src/utils/tile/getRasterTile.ts
=> Fix raster color

dev-demos/bugs/line/demo/gaodev1.tsx, dev-demos/bugs/line/line.md, dev-demos/bugs/polygon/demos/scale.tsx, dev-demos/bugs/polygon/scale.md, dev-demos/features/line/demos/linedash.tsx, package.json, packages/component/src/control/logo.ts, packages/core/src/services/scene/SceneService.ts, packages/maps/.fatherrc.ts, packages/maps/package.json, packages/maps/src/utils/amap/AMapBaseService.ts, packages/site/docs/api/tile/geojsonvt_tile_layer.zh.md
=> fix: 添加l7-maps 地图  umd

package.json, packages/site/docs/api/scene.zh.md
=> docs: 场景 Scene API 补充 addPopup 和 removePopup 方法说明

dev-demos/features/point/demos/icons.tsx, packages/layers/src/utils/updateShape.ts
=> fix: 修复 shape 更新失效

packages/component/src/control/exportImage.ts
=> fix: getImage async method

packages/layers/src/point/__tests__/layer_init.spec.ts
=> fix: 修复 gl jest-test 测试

packages/layers/src/line/models/line.ts
=> fix: 修复鸿蒙系统 webgl 扩展不支持错误

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish update version 2.13.0 -> 2.13.1

packages/site/docs/api/line_layer/source.zh.md, packages/site/docs/api/polygon_layer/source.zh.md, packages/site/examples/tutorial/layer/demo/layer_boxselect.js, packages/site/examples/tutorial/layer/demo/meta.json, packages/site/package.json
=> docs: 修复文档部分问题

dev-demos/tile/Vector/demos/citytile.tsx, packages/site/docs/api/source/mvt.zh.md, packages/source/src/parser/mvt.ts
=> feat: mvt 实现getCustomdata 方法

package.json
=> chore: remove extra libs

packages/site/examples/tutorial/control/demo/amap.js
=> fix: fix website demo err

packages/core/src/services/debug/DebugService.ts, packages/core/src/services/debug/IDebugService.ts
=> chore: 修改 debugService 的类型定义

dev-demos/features/line/demos/linedash.tsx, packages/core/src/services/debug/DebugService.ts, packages/core/src/services/debug/IDebugService.ts, packages/core/src/services/layer/ILayerService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/DataMappingPlugin.ts, packages/layers/src/plugins/DataSourcePlugin.ts, packages/layers/src/plugins/FeatureScalePlugin.ts, packages/layers/src/plugins/LayerModelPlugin.ts
=> refactor: 修改 debugService 日志结构

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.13.6 -> 2.13.7

packages/layers/src/core/BaseLayer.ts, packages/scene/src/index.ts
=> fix: debug service undefined

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.13.7 -> 2.13.8

dev-demos/features/fix/demos/fix2.tsx, packages/component/src/marker.ts, packages/utils/src/env.ts
=> fix: 修复高德2.x 下，Marker 在 IOS 终端的 click 事件失效

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.13.8 -> 2.13.9

dev-demos/bugs/heatmap/demos/hexagon.tsx, dev-demos/bugs/heatmap/hexagon.md, dev-demos/bugs/scene/demos/exportimg.tsx, dev-demos/tile/BaseMap/demos/normal.tsx, packages/layers/src/core/BaseLayer.ts, packages/map/src/camera.ts
=> fix: 地图pitch,zoom 为 0 时不生效

dev-demos/features/line/demos/greatcircleline.tsx, dev-demos/features/line/demos/simplelines.tsx, dev-demos/features/line/simpleline.md, packages/component/__tests__/mouseLocation.spec.ts, packages/site/docs/api/experiment/earth/earth.zh.md, packages/site/docs/tutorial/map/amapplugin.zh.md, packages/site/examples/amap-plugin/bus/demo/satellite.js, packages/site/examples/amap-plugin/bus/demo/xyztile.js, packages/site/examples/engine/three/demo/space_click.js, packages/site/examples/tile/vector/demo/simpleline.ts
=> docs: demo update 

dev-demos/tile/Raster/demos/rasterData.tsx, packages/layers/src/tile/tileLayer/BaseLayer.ts, packages/site/examples/tile/vector/demo/simpleline.ts
#1639  栅格瓦片执行scene.removeLayer()后未被真正移除
=> fix: remove listener while Tile destroy

dev-demos/tile/Raster/demos/terrainRgb.tsx, dev-demos/tile/Raster/terrainrgb.md, packages/core/src/services/source/ISourceService.ts, packages/layers/src/tile/tileFactory/index.ts, packages/source/src/parser/raster-tile.ts, packages/source/src/utils/tile/getCustomData.ts, packages/utils/src/ajax.ts
=> feat: terrainRGB 支持自定义数据获取方式

packages/component/src/marker.ts, packages/core/src/services/layer/LayerService.ts
=> fix: 图层visible&marker 事件

packages/map/package.json
=> chore: 添加 map 库同步脚本

packages/site/docs/api/scene.zh.md
=> docs: 修正官网文案

dev-demos/component/control/position.tsx, packages/component/src/control/baseControl/control.ts
=> fix: 修复各个 position 下 Control 容器的排列方向问题

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: 升级版本号

dev-demos/bugs/point/demos/circle.tsx, lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/layers/src/core/BaseModel.ts, packages/layers/src/point/models/fill.ts, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> Publish 2.17.2

packages/layers/src/line/models/arc.ts, packages/layers/src/line/models/line.ts, packages/layers/src/line/models/linearline.ts, packages/layers/src/line/models/simpleLine.ts
=> fix: 线图层 opacity

packages/component/src/control/baseControl/index.ts, packages/component/src/index.ts
=> fix: 修复 export 冲突问题

dev-demos/features/line/demos/linedash.tsx, packages/layers/src/core/BaseLayer.ts, packages/layers/src/line/models/line.ts, packages/layers/src/line/shaders/dash/line_dash_vert.glsl, packages/layers/src/line/shaders/line_frag.glsl, packages/layers/src/line/shaders/line_vert.glsl, packages/layers/src/line/shaders/linear/line_linear_frag.glsl, packages/layers/src/plugins/LayerModelPlugin.ts, packages/layers/src/plugins/LayerStylePlugin.ts
=> fix: 虚线图层style 更新

.umirc.ts, dev-demos/draw/demo/destroy.tsx, dev-demos/draw/destroy.md, packages/layers/src/core/BaseLayer.ts, packages/renderer/src/regl/ReglBuffer.ts
=> Fix destroy

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.17.5

dev-demos/bugs/three/demo/marker.tsx, dev-demos/bugs/three/marker.md, packages/three/src/core/baseLayer.ts
=> fix: threejs build layer

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update version 2.17.7

package.json, packages/layers/src/tile/tileLayer/BaseLayer.ts
=> fix: 修复图层不可见时请求不必要瓦片资源问题

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: update 版本 2.17.8

packages/l7/.fatherrc.ts, packages/l7/__tests__/version.spec.ts, packages/l7/src/version.ts
=> chore: 通过打包配置更新版本

dev-demos/tile/Vector/demos/pmtiles.tsx, dev-demos/tile/Vector/pmtiles.md, package.json, packages/scene/src/index.ts, packages/site/.dumi/global.ts, packages/site/docs/api/scene.zh.md, packages/site/examples/tile/vector/demo/meta.json, packages/site/examples/tile/vector/demo/pmtiles.ts, packages/site/package.json, packages/source/src/parser/mvt.ts, packages/source/src/utils/tile/getRasterTile.ts, packages/utils/src/ajax.ts, packages/utils/src/config.ts, packages/utils/src/index.ts, packages/utils/src/tileset-manager/utils/tile-url.ts
=> Feat pmtile

.github/ISSUE_TEMPLATE.md, .github/workflows/main.yml
=> docs: update issue template

.github/ISSUE_TEMPLATE.md, .github/workflows/main.yml
=> Chore workfolws

.github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE_EN.md, .github/workflows/chatgpt.yml, .github/workflows/issue.yml
=> chore: add issue action

packages/component/src/utils/popper.ts, packages/utils/src/dom.ts
=> fix: 修复 PopperControl unclick 时，弹出框不关闭的问题

packages/site/.dumi/pages/Examples/components/GalleryPageContent/index.tsx, packages/site/.dumi/pages/Examples/components/SelectExampleBar/index.module.less, packages/site/.dumi/pages/Examples/components/SelectExampleBar/index.tsx, packages/site/.dumi/pages/Examples/index.tsx, packages/site/.dumirc.ts
=> docs: example 新增搜索功能

packages/source/src/parser/geojson.ts, packages/source/src/parser/json.ts, packages/source/src/utils/util.ts
rewind  方法会修改原始数据，修改判断规则 frozen 的数据，需要深度克隆后才能修改
---
=> fix: 修复 frozen 的 geojson 数据

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish

dev-demos/features/point/demos/circlemeter.tsx, dev-demos/features/polygon/demos/indoor.tsx, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/FeatureScalePlugin.ts, packages/layers/src/polygon/index.ts, packages/layers/src/polygon/shaders/extrusion/polygon_extrusion_vert.glsl, packages/site/.dumi/pages/Examples/index.module.less, packages/site/docs/api/point_layer/style.zh.md, packages/site/docs/api/polygon_layer/shape.zh.md, packages/site/docs/api/polygon_layer/style.zh.md, packages/site/examples/gallery/animate/demo/meta.json, packages/site/examples/point/dot/demo/normal.js, packages/site/examples/point/text/demo/point_text.js, packages/site/examples/polygon/extrusion/demo/meta.json, packages/site/examples/polygon/extrusion/demo/polygon.js, packages/site/examples/polygon/extrusion/index.en.md, packages/site/examples/polygon/extrusion/index.zh.md
=> fix: scale 为 identity 时的问题 & extrusion demo

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/examples/gallery/basic/demo/normal.js, packages/site/examples/polygon/extrusion/demo/meta.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> docs:  更新demo

packages/l7/.fatherrc.ts, packages/l7/demo/text2.html, packages/maps/src/index.ts
---
https://webpack.docschina.org/configuration/externals/#object
=> chore: umd 打包

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/.fatherrc.ts, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/.fatherrc.ts, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> Publish 2.19.3 riddle 配置

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/oscp.yml
=> chore: add issue template

.umirc.ts, dev-demos/bugs/scene/bmap.md, dev-demos/bugs/scene/demos/bmap.tsx, package.json, packages/maps/src/bmap/index.ts, packages/maps/src/bmap/map.ts, packages/maps/src/index.ts, packages/maps/typings/index.d.ts
=> feat: 新增 BMap

packages/site/docs/api/component/map_theme.en.md, packages/site/docs/tutorial/polygon/extrude.en.md, packages/site/docs/tutorial/polygon/fill.en.md, packages/site/docs/tutorial/polygon/water.zh.md
=> docs: 英文文档标题

packages/site/examples/gallery/story/demo/gaza.js, packages/site/examples/gallery/story/demo/meta.json, packages/site/examples/gallery/story/demo/yidaiyilu.js, packages/site/examples/gallery/story/index.en.md, packages/site/examples/gallery/story/index.zh.md, packages/site/examples/tile/vector/demo/worldmap.ts
=> docs: 新增demo

dev-demos/features/line/demos/line.tsx, dev-demos/features/line/demos/simplelines.tsx, packages/layers/src/line/shaders/simple/simpleline_linear_frag.glsl, packages/layers/src/line/shaders/simple/simpleline_vert.glsl
=> fix(layer): fix simple line 渐变色

packages/maps/src/amap2/map.ts, packages/site/.dumirc.ts
=> fix: updtate JS API  token

packages/site/examples/gallery/story/demo/yidaiyilu2.js
=> docs: 更新地图配置

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish 2.19.7

packages/component/src/control/layerSwitch.ts
=> feat: layerSwitch 新增支持传入 layerSwitchItem 属性

packages/component/src/popup/layerPopup.ts
=> fix: 修复 LayerPopup items 为空时，followCursor 问题

packages/site/docs/common/layer/raster/rampcolors.en.md, packages/site/docs/common/layer/raster/rampcolors.zh.md
=> docs: 删除 RasterLayer 旧文档样式描述

packages/source/src/parser/image.ts
=> fix:  credentials: include 产生跨域问题

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/.fatherrc.ts, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish 2.19.9

packages/maps/src/tmap/map.ts
#2007
Fix tencent map bugs with L7 draw. However, there's something wrong when squares or circles are dragged after they've been created. Tencent map won't moved by dragging while other interactions are fine. Seems like there's something blocking the cameraChange event. Currently I'm digging it.
---
=> fix(packages/maps): fix l7 draw layer bug on tencent map

dev-demos/bugs/point/demos/text.tsx, dev-demos/features/point/circle.md, dev-demos/features/point/demos/circlemeter.tsx, dev-demos/features/point/pointCircleWebGPU.md, dev-demos/features/point/pointNormalDevice.md, packages/core/package.json, packages/core/src/services/asset/FontService.ts, packages/core/src/services/renderer/IModel.ts, packages/core/src/services/shader/ShaderModuleService.ts, packages/core/src/shaders/opacity_attr.vert.glsl, packages/core/src/shaders/picking.frag.glsl, packages/core/src/shaders/picking.vert.glsl, packages/core/src/shaders/picking_uniforms.glsl, packages/core/src/shaders/projection.glsl, packages/core/src/shaders/scene_uniforms.glsl, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/PixelPickingPlugin.ts, packages/layers/src/point/shaders/fill_frag.glsl, packages/renderer/src/device/DeviceModel.ts, packages/renderer/src/device/index.ts
=> fix 英文文章标注对其问题

packages/site/docs/api/component/layer_switch.zh.md
=> fix: 修复 LayerPopup unclick 不消失问题

packages/component/src/control/layerSwitch.ts
=> fix: 修复 LayerSwitch 误识别 L7Plot 问题

packages/site/.dumirc.ts, packages/site/package.json
=> chore: update dumi-theme-antv

packages/site/.dumirc.ts, packages/site/package.json
=> docs: image position change

dev-demos/component/popup/layerPopup.tsx, packages/component/src/popup/layerPopup.ts
=> fix: 修复 LayerPopup trigger & items 导致的 Bug

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish v2.20.2

packages/core/src/shaders/projection.glsl, packages/layers/src/point/shaders/extrude/extrude_vert.glsl, packages/site/docs/api/map/bmap.en.md, packages/site/docs/api/map/gaode.en.md, packages/site/docs/api/map/map.en.md, packages/site/docs/api/map/mapbox.en.md, packages/site/docs/api/map/maplibre.en.md, packages/site/docs/api/map/tencent.en.md, packages/site/docs/common/map.en.md, packages/site/examples/polygon/3d/demo/polygon_stylemap.js
=> docs: 文档更新

packages/component/src/css/index.css, packages/component/src/css/select.less, packages/component/src/css/variables.less
=> fix: 修复 MapTheme 换行样式问题

dev-demos/features/point/demos/circlemeter.tsx, dev-demos/features/point/demos/column.tsx, dev-demos/features/point/pointColumn.md, packages/layers/src/core/BaseModel.ts, packages/layers/src/core/CommonStyleAttribute.ts, packages/layers/src/core/constant.ts, packages/layers/src/core/utils.ts, packages/layers/src/point/models/extrude.ts, packages/layers/src/point/models/image.ts, packages/layers/src/point/shaders/extrude/extrude_frag.glsl, packages/layers/src/point/shaders/extrude/extrude_vert.glsl
=> chore: pointlayer extruder 支持 device render

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> Publish 2.20.5

dev-demos/bugs/polygon/demos/quantile.tsx, dev-demos/bugs/polygon/quantile.md, packages/layers/src/plugins/FeatureScalePlugin.ts
=> fix: quantile scale mutlipoygon 不准确 fix: #2086

dev-demos/features/point/demos/circlemeter.tsx, package.json, packages/scene/src/index.ts, packages/site/docs/api/scene.en.md, packages/site/docs/api/scene.zh.md
=> feat: scene 提供 animate 控制方法,用于调试

dev-demos/features/point/demos/radar.tsx, dev-demos/features/point/pointRadar.md, packages/core/src/services/layer/IStyleAttributeService.ts, packages/core/src/services/layer/StyleAttributeService.ts, packages/core/src/services/renderer/IModel.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/core/BaseModel.ts, packages/layers/src/core/CommonStyleAttribute.ts, packages/layers/src/line/models/wall.ts, packages/layers/src/point/models/fillmage.ts, packages/layers/src/point/models/radar.ts, packages/layers/src/point/shaders/fill_frag.glsl, packages/layers/src/point/shaders/image/fillImage_frag.glsl, packages/layers/src/point/shaders/image/fillImage_vert.glsl, packages/layers/src/point/shaders/radar/radar_frag.glsl, packages/layers/src/point/shaders/radar/radar_vert.glsl
=> Feat: fillImage&radar update to G-Engine

packages/layers/src/point/models/radar.ts, packages/layers/src/point/shaders/radar/radar_frag.glsl, packages/layers/src/point/shaders/radar/radar_vert.glsl
=> fix: radar 数据映射

dev-demos/features/polygon/demos/ocean.tsx, dev-demos/features/polygon/demos/water.tsx, package.json, packages/layers/src/polygon/models/ocean.ts, packages/layers/src/polygon/models/water.ts, packages/layers/src/polygon/shaders/extrude/polygon_extrudetex_frag.glsl, packages/layers/src/polygon/shaders/water/polygon_ocean_frag.glsl, packages/layers/src/polygon/shaders/water/polygon_ocean_vert.glsl, packages/layers/src/polygon/shaders/water/polygon_water_frag.glsl, packages/layers/src/polygon/shaders/water/polygon_water_vert.glsl, packages/renderer/package.json, packages/renderer/src/regl/ReglModel.ts
=> chore: ocean

packages/layers/src/point/models/image.ts, packages/layers/src/point/shaders/image_frag.glsl, packages/layers/src/point/shaders/image_vert.glsl
=> chore: pointLayer image

dev-demos/features/geometry/demos/billboard.tsx, packages/layers/src/geometry/models/billboard.ts, packages/layers/src/geometry/shaders/billboard_frag.glsl, packages/layers/src/geometry/shaders/billboard_vert.glsl
=> 【WIP】chore: 升级geometry的billboard支持G引擎

dev-demos/features/geometry/demos/billboard.tsx, packages/layers/src/core/BaseModel.ts, packages/layers/src/geometry/models/billboard.ts, packages/layers/src/geometry/shaders/billboard_frag.glsl, packages/layers/src/geometry/shaders/billboard_vert.glsl
=> fix: billboard rotation

dev-demos/features/geometry/demos/plane.tsx, dev-demos/features/geometry/plane.md, packages/layers/src/geometry/models/plane.ts, packages/layers/src/geometry/shaders/plane_frag.glsl, packages/layers/src/geometry/shaders/plane_vert.glsl
=> chore: 升级geometry的plane支持G引擎

dev-demos/features/geometry/demos/sprite.tsx, packages/layers/src/geometry/models/sprite.ts, packages/layers/src/geometry/shaders/sprite_frag.glsl, packages/layers/src/geometry/shaders/sprite_vert.glsl
=> [WIP] Chore: 尝试升级geometry的sprite类型

dev-demos/features/citybuilding/amap1.tsx, dev-demos/features/citybuilding/amap2.tsx, dev-demos/features/geometry/demos/plane.tsx, dev-demos/features/geometry/demos/sprite.tsx, dev-demos/features/geometry/plane.md, dev-demos/features/point/demos/billboard.tsx, dev-demos/features/point/demos/cylinder.tsx, dev-demos/features/point/demos/iconfont.tsx, dev-demos/features/point/demos/icons.tsx, dev-demos/features/point/demos/normal.tsx, dev-demos/features/point/pointBillboard.md, dev-demos/features/point/pointCircle.md, dev-demos/features/point/pointEarthfill.md, dev-demos/features/point/pointImage.md, dev-demos/features/point/pointWave.md, packages/layers/src/geometry/models/plane.ts, packages/layers/src/geometry/models/sprite.ts, packages/layers/src/geometry/shaders/plane_frag.glsl, packages/layers/src/geometry/shaders/plane_vert.glsl, packages/layers/src/geometry/shaders/sprite_frag.glsl, packages/layers/src/geometry/shaders/sprite_vert.glsl, packages/layers/src/point/models/billboard_point.ts, packages/layers/src/point/models/fill.ts, packages/layers/src/point/shaders/animate/wave_frag.glsl, packages/layers/src/point/shaders/billboard_point_frag.glsl, packages/layers/src/point/shaders/billboard_point_vert.glsl, packages/layers/src/point/shaders/fill_frag.glsl, packages/layers/src/point/shaders/fill_vert.glsl
=> Chore point layer

dev-demos/features/point/pointColumn.md, packages/layers/src/plugins/DataMappingPlugin.ts
=> fix: setData 为空

dev-demos/features/point/pointColumn.md, packages/layers/src/plugins/DataMappingPlugin.ts, packages/layers/src/point/models/billboard_point.ts, packages/layers/src/point/models/earthExtrude.ts, packages/layers/src/point/models/earthFill.ts, packages/layers/src/point/models/normal.ts
=> Fix setdata

examples/view.tsx, lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/l7/src/version.ts, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/mini/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> fix: version & publish 2.20.8

examples/demos/bugfix/color.ts, examples/demos/bugfix/index.ts, examples/demos/index.ts, examples/demos/point/fill.ts, examples/demos/point/image.ts, packages/core/src/services/layer/StyleAttributeService.ts
=> fix: 大数据量 updateAttributeByFeatureRange 内存溢出

examples/demos/raster/dem.ts, examples/demos/raster/image.ts, examples/demos/raster/tiff.ts, packages/core/src/services/renderer/IRendererService.ts, packages/core/src/services/renderer/ITexture2D.ts, packages/core/src/services/renderer/gl.ts, packages/layers/src/raster/models/raster.ts, packages/renderer/src/device/DeviceTexture2D.ts, packages/renderer/src/device/index.ts, packages/renderer/src/regl/index.ts
WebGL1 下启用 OES_texture_float 时允许 `gl.LUMINANCE` 和 `gl.FLOAT` 的组合，但在 WebGL2 下会报错，此时需要改成 `gl.RED`。
---
=> fix: single component data texture

__tests__/e2e/tests.ts, examples/demos/raster/index.ts, examples/demos/raster/multiband.ts, packages/layers/src/raster/index.ts, packages/layers/src/raster/models/rasterRgb.ts, packages/site/docs/api/other/city_building.en.md, packages/site/docs/api/other/city_building.zh.md, packages/source/src/index.ts, packages/source/src/parser/raster/rgb.ts, packages/source/src/utils/bandOperation/operationSchema.ts
=> chore: multiband rgb raster parse

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish 2.20.11

dev-demos/component/popup/layerPopup.tsx, packages/component/src/popup/layerPopup.ts
=> fix: 修复图层隐藏时，LayerPopup 未跟随隐藏的问题

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish 2.20.13

packages/site/examples/engine/three/demo/basic_geometry.js, packages/site/examples/engine/three/demo/meta.json
=> chore: add threejs demo

packages/site/examples/engine/three/demo/basic_geometry.js, packages/site/examples/engine/three/demo/meta.json
=> chore: update threejs demo

examples/demos/index.ts, packages/maps/package.json, packages/maps/src/gmap/index.ts, packages/maps/src/gmap/logo.css, packages/maps/src/gmap/map.ts, packages/maps/src/gmap/maploader.ts, packages/maps/src/index.ts, packages/maps/typings/index.d.ts
=> feat: add google map

.npmrc, examples/demos/point/fill.ts, lerna.json, packages/component/package.json, packages/core/package.json, packages/core/src/services/interaction/InteractionService.ts, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> Publish 2.20.15

packages/component/src/popup/layerPopup.ts
=> fix: 修复 LayerPopup 因 Popup setOptions 误触发 show() 的问题

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish 2.20.17

dev-demos/component/sync-scene/helper.ts, dev-demos/component/sync-scene/syncScene.tsx, dev-demos/component/sync-scene/syncSene.md, dev-demos/component/sync-scene/types.ts, packages/site/examples/component/control/demo/meta.json, packages/site/examples/component/control/demo/syncScene.ts
=> feat: 同步地图demo

packages/site/.dumi/theme/slots/GithubButtonBar.tsx, packages/site/.dumirc.ts, packages/site/docs/api/react/react.en.md, packages/site/docs/api/react/react.zh.md, packages/site/examples/component/control/demo/meta.json, packages/site/examples/component/control/demo/syncScene.ts, packages/site/examples/line/path/demo/meta.json, packages/site/examples/map/map/demo/meta.json, packages/site/examples/raster/data/demo/aqi.js, packages/site/examples/raster/data/demo/meta.json, packages/site/examples/raster/data/demo/temp.js
=> Chore docs

packages/component/src/marker.ts, packages/site/.dumi/theme/slots/GithubButtonBar.tsx, packages/site/.dumirc.ts, packages/site/docs/api/react/react.en.md, packages/site/docs/api/react/react.zh.md, packages/site/examples/component/control/demo/meta.json, packages/site/examples/component/control/demo/syncScene.ts, packages/site/examples/line/path/demo/meta.json, packages/site/examples/map/map/demo/meta.json, packages/site/examples/raster/data/demo/aqi.js, packages/site/examples/raster/data/demo/meta.json, packages/site/examples/raster/data/demo/temp.js
=> Fix marker

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish 2.20.18

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish 2.20.19

packages/core/src/services/interaction/PickingService.ts
=> fix: getViewportSize dpr

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish 2.20.20

packages/component/src/marker.ts
=> chore: remove debug log

examples/demos/bugfix/event_legend.ts, examples/demos/bugfix/index.ts, examples/utils/sleep.ts, packages/core/src/services/layer/IStyleAttributeService.ts, packages/core/src/services/layer/StyleAttributeService.ts, packages/layers/src/core/BaseLayer.ts, packages/site/docs/api/common/layer/layer_event.en.md, packages/site/docs/api/common/layer/layer_event.zh.md
=> fix: legend event

lerna.json, packages/component/package.json, packages/core/package.json, packages/l7/package.json, packages/layers/package.json, packages/map/package.json, packages/maps/package.json, packages/renderer/package.json, packages/scene/package.json, packages/site/package.json, packages/source/package.json, packages/test-utils/package.json, packages/three/package.json, packages/utils/package.json
=> chore: publish 2.21.0

examples/demos/point/fill.ts, packages/component/src/marker.ts, packages/core/src/services/interaction/PickingService.ts, packages/core/src/shaders/picking.frag.glsl, packages/core/src/shaders/picking.vert.glsl, packages/core/src/shaders/picking_uniforms.glsl, packages/layers/src/plugins/PixelPickingPlugin.ts, packages/site/docs/api/component/marker_layer.en.md, packages/site/docs/api/component/marker_layer.zh.md
| 🇨🇳 中文 |   图层可以同时支持 active 和 select 交互       |
---
=> docs: 补充 marker cluster 文档 & active，select  交互  fix #969

packages/site/.dumi/pages/custom/docs/sdk.md, packages/site/.dumi/pages/custom/docs/service.md, packages/site/maptools/demo/index.tsx, packages/site/maptools/demo/util.ts, packages/site/package.json
=> fix: 修改 DistrictData demo 和文档

packages/site/docs/api/map/leaflet.en.md, packages/site/docs/api/map/leaflet.zh.md, packages/site/maptools/component/Hero/index.tsx
=> docs: 修改 Leaflet 和 district-data 的gitHub地址

.github/workflows/update-snapshots.yml
=> ci: fix branch_name

.github/workflows/update-snapshots.yml
=> ci: fix branch name

packages/maps/src/maplibre/map.ts
=> fix: 修复 MapLibre 下使用 CanvasLayer 鼠标事件异常问题

.changeset/late-windows-hunt.md, packages/source/src/utils/tile/getRasterTile.ts
=> fix: 修复rastertile类型对应请求无法自定义请求头参数

.changeset/tame-trees-fold.md, packages/source/src/parser/raster-tile.ts, packages/source/src/utils/tile/getRasterTile.ts
=> fix: 修复 arraybuffer 类型数据自定义请求头参数透传逻辑

.github/workflows/release-notify.yml, .github/workflows/release.yml
=> ci: fix get main version

site/public/weather/index.html
=> 修改天气地图 title

site/docs/api/map/leaflet.zh.md
=> chore:修复文档map.leaflet文案错误

.changeset/eighty-oranges-search.md, .changeset/grumpy-tables-dream.md
=> chore: add changeset

.github/workflows/release-notify.yml
=> ci: action unexpected EOF while looking for matching

.changeset/five-singers-rush.md, examples/demos/components/marker.ts, packages/component/src/control/mouseLocation.ts, packages/component/src/marker.ts
=> fix: 无地图与 MapLibre 模式移动 Marker 出错

.changeset/rude-crabs-cheer.md, examples/main.tsx, examples/utils/scene.ts, packages/maps/src/tdtmap/map.ts
=> fix: 天地图 setCenter 方法缺失

site/package.json
=> chore: 升级 dumi 至 2.3.8

site/docs/api/tile/geojsonvt_tile_layer.zh.md
=> fix: GeoJsonVT 瓦片中文文档表格错乱

site/docs/api/tile/geojsonvt_tile_layer.zh.md
=> docs: format table style

site/.dumirc.ts
=> feat: add the petercat

site/.dumirc.ts
=> fix: relativePath in themeConfig

examples/demos/point/fill.ts, packages/map/src/index.ts, packages/maps/src/tmap/map.ts
https://github.com/antvis/L7/issues/2567
把mouseover事件绑定给map容器。
| 🇺🇸 英文 |  fix tmap mouseover event don't work        |
| 🇨🇳 中文 |  修复腾讯地图 mouseover 事件失效       |
---
=> fix: tmap mouseover not work
