src/geo/featureIndex.js
在src/geo/featureIndex.js文件中，使用rbush创建要素时，导入的rbush应该使用new 关键字
=> 修复要素创建索引的笔误

bin/shader2js.js, demos/03_choropleths_polygon.html, demos/dashline.html, demos/markertest.html, demos/text.html, package.json, rollup.config.js, src/component/control/base.js, src/component/css/l7.css, src/core/controller/mapping.js, src/core/layer.js, src/core/scene.js, src/geom/shader/meshline_vert.glsl, src/geom/shader/text_frag.glsl, src/layer/image_layer.js, src/layer/line_layer.js, src/layer/render/text/drawText.js, src/map/AMap.js
地图组件增加管理隐藏显示功能
修复地图样式设置问题
修复图片不能立即渲染问题
=> fix map bug

gatsby-config.js
=> fix: duplicated gatsby config

.github/CONTRIBUTING.md, .travis.yml, README.md, README.zh-CN.md, jest.config.js, package.json, stories/Components/components/Marker.tsx, stories/Components/components/Popup.tsx, yarn.lock
re #101 
* 使用 `cross-env` 设置 `BABEL_ENV`
* 补充 Windows 下开发 `CONTRIBUTING.md`
=> 修复 Windows 环境开发问题

packages/core/src/utils/dom.ts
Scene传入的style背景色不生效，需要画布继承才生效。
=> feat: 地图画布的底色继承外面的颜色

packages/core/src/services/config/ConfigService.ts, packages/core/src/services/config/IConfigService.ts, packages/core/src/services/layer/ILayerService.ts, packages/core/src/services/map/IMapService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/LayerStylePlugin.ts, packages/maps/src/amap/map.ts, packages/maps/src/mapbox/map.ts, packages/react/src/component/LayerAttribute/Layer.tsx, packages/react/src/component/LayerAttribute/Source.tsx, packages/react/src/component/LayerAttribute/index.ts, packages/scene/src/IMapController.ts, packages/scene/src/index.ts, stories/React/components/world_ncov_fill.tsx
feat: mapbox添加fitBoundsOptions;
可在new Scene的时候传入；也可在Layer中传入，也可直接在fitBounds时传入。
支持Mapbox的fitBounds，不支持对AMap的调整。
=> feat: mapbox添加fitBoundsOptions

packages/core/src/services/source/ISourceService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/DataSourcePlugin.ts, packages/source/__tests__/source.spec.ts, packages/source/src/source.ts
如果按照视野范围进行计算聚合数据会出现新的问题，比如当计算出的数据范围大于视野范围时，里面的判断会return，导致不聚合现象的产生。此次pr取消了上次pr的一部分，转而使用计算出的数据范围 * 2，可以避免此类现象的产生。
fix #511
=> fix(layer): 用计算出的数据范围 * 2代替之前的视野范围

examples/point/text/demo/point_text.js, packages/layers/src/core/BaseLayer.ts, packages/layers/src/point/models/text.ts, packages/layers/src/point/shaders/text_vert.glsl
增加文本旋转的功能，支持 rotate 配置方法
```
const pointLayer = new PointLayer({})
.source(data.list, {
parser: {
type: 'json',
x: 'j',
y: 'w'
}
})
.shape('m', 'text')
.size(12)
// .rotate("j",()=>{
//   return  Math.random()*3*(Math.random()>0.5?1:-1)
// })
.color('w', [ '#0e0030', '#0e0030', '#0e0030' ])
.style({
textAnchor: 'center', // 文本相对锚点的位置 center|left|right|top|bottom|top-left
textOffset: [ 0, 0 ], // 文本相对锚点的偏移量 [水平, 垂直]
spacing: 2, // 字符间距
padding: [ 1, 1 ], // 文本包围盒 padding [水平，垂直]，影响碰撞检测结果，避免相邻文本靠的太近
stroke: '#ffffff', // 描边颜色
strokeWidth: 0.3, // 描边宽度
strokeOpacity: 1.0
});
scene.addLayer(pointLayer);
```
=> feat: add text point rotate function

packages/layers/src/point/models/text.ts, packages/layers/src/utils/symbol-layout.ts, stories/Layers/components/Text.tsx
- Close #693
- 目前文本默认是居中的，但计算多行文本中每个文字的位置会有问题，所以改成 `left`
- 换行文本的 `y` 计算有误，应该是减去行高，之前导致文本渲染行的顺序是反的
- 目前文本 layer的 size 实际是配置行高，不是字体大小，可以加这个参数
-  文本对齐的配置也可以由用户配置，目前是 hard code 在代码里
- 文本对齐算法估计要重新弄一下
=> feat: `PointLayer` support multi lines

packages/core/src/services/layer/ILayerService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/FeatureScalePlugin.ts, stories/Scale/Scale.stories.tsx, stories/Scale/components/Quantize.tsx
**修复获取图例类型问题**
- 当 scale [Continuous](https://github.com/d3/d3-scale#continuous-scales) ([Linear](https://github.com/d3/d3-scale#linear-scales), [Power](https://github.com/d3/d3-scale#power-scales), [Log](https://github.com/d3/d3-scale#log-scales), [Identity](https://github.com/d3/d3-scale#identity-scales), [Time](https://github.com/d3/d3-scale#time-scales), [Radial](https://github.com/d3/d3-scale#radial-scales)) 时，拥有 ticks 方法
- 当 scale [Quantize](https://github.com/d3/d3-scale#quantize-scales)、[Quantile](https://github.com/d3/d3-scale#quantile-scales)、[Threshold](https://github.com/d3/d3-scale#threshold-scales) 时，scale 拥有 invertExtent 与 ticks 方法，会导致获取图例数据错误
=> fix: legend type

packages/core/src/services/interaction/PickingService.ts, packages/core/src/services/layer/ILayerService.ts, packages/core/src/services/layer/LayerService.ts, packages/scene/src/index.ts, stories/Map/components/mapCenter.tsx
=> feat: 给场景新增 getPickedLayerId 方法

packages/layers/src/polygon/models/extrude.ts, packages/layers/src/polygon/shaders/extrude/polygon_extrude_frag.glsl, packages/layers/src/polygon/shaders/extrude/polygon_extrude_picklight_frag.glsl, packages/layers/src/polygon/shaders/extrude/polygon_extrude_picklight_vert.glsl, packages/layers/src/polygon/shaders/extrude/polygon_extrude_vert.glsl, packages/layers/src/polygon/shaders/extrude/polygon_extrudetex_frag.glsl, packages/layers/src/polygon/shaders/extrude/polygon_extrudetex_vert.glsl, stories/Map/components/amap2demo_polygon_extrude.tsx, stories/Map/components/polygon_extrudeTex.tsx
=> Polygonside

packages/core/src/services/interaction/PickingService.ts, stories/Map/components/amap2demo_polygon.tsx
错误状态的触发：
1. 两个不同的图层存在重叠部分
2. 从后渲染的图层经过重叠部分移到先渲染的图层时触发
1. 在 pickService 中新增 pickedLayers 记录被拾取选中的 layer
2. 每次在进行拾取操作的时候先进行清除选中状态的操作
```javascript
private async pickingLayers(target: IInteractionTarget) {
...
// Tip: clear last picked layer state
this.pickedLayers.map((pickedlayer) => {
this.selectFeature(pickedlayer, new Uint8Array([0, 0, 0, 0]));
});
...
}
```
=> fix: 修复拾取状态残留导致的拾取高亮错误

packages/layers/package.json
```merge-json-schemas``` Never used in codes, it's too old and unnecessary. make some npm WARN.
```npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.```
=> [chores] Remove unused dependencie

dev-demos/features/customLayer/marker-layer.md, packages/component/src/marker-layer.ts
fix: markerLayer在GaodeMapV2做底图时removeMarkerLayer视图图层层级改变时会复原被删除的图层及去除clear方法中调用注销监听事件
=> fix: markerLayer在GaodeMapV2做底图时removeMarkerLayer视图图层层级改变时会复原被删除的图层

packages/component/src/popup/layerPopup.ts
=> fix: 修复 LayerPopup 中的类型 BaseLayer => ILayer

dev-demos/features/point/demos/text2.tsx, dev-demos/features/point/pointText2.md, packages/core/src/services/layer/ILayerService.ts, packages/layers/src/core/BaseLayer.ts, packages/layers/src/core/BaseModel.ts, packages/layers/src/line/index.ts, packages/layers/src/line/models/arc_3d.ts, packages/layers/src/point/index.ts, packages/layers/src/point/models/text.ts, packages/layers/src/polygon/index.ts
=> feat: 文字支持textoffset,anchor

packages/l7/package.json
=> Add missing git repo info

packages/source/src/parser/image.ts
目前图片图层在[跨域请求图片](https://developer.mozilla.org/zh-CN/docs/Web/API/Request/credentials)的情况下，不会带上 cookies
现在需要确定的是，source 是否需要添加上这个配置，还是默认内置带上 cookies
---
=> fix: 图片图层在跨域请求的情况下不发送 cookies

packages/source/src/parser/image.ts
图片图层在跨域请求的情况下不发送 cookies，现在允许图片图层在请求数据时自定义请求参数
带 cookies 使用方式如下：
```ts
const layer = new ImageLayer({})
.source(
'https://gw.alipayobjects.com/zos/rmsportal/FnHFeFklTzKDdUESRNDv.jpg',
{
parser: {
type: 'image',
extent: [ 121.168, 30.2828, 121.384, 30.4219 ],
requestParameters: { credentials: "include" }
}
}
);
```
=> feat: 图片图层请求数据支持自定义参数

packages/site/examples/mask/basic/demo/rastertile_raster.ts, packages/site/examples/raster/single_raster/demo/light.js, packages/site/examples/raster/single_raster/demo/light_default.js
=> docs: 修改文档示例拼写错误 nodataValue => noDataValue

.github/CONTRIBUTING.md
- [ √] 站点、文档改进
close #2028 
提供 window 环境下，主要提供相关依赖如何安装，能指导 windows 用户进行 L7 研发
| 🇨🇳 中文 |     更新中文版开发者文档     |
- [ √] 文档已补充或无须补充
- [√ ] 代码演示已提供或无须提供
- [√ ] TypeScript 定义已补充或无须补充
- [√ ] Changelog 已提供或无须提供
---
=> docs: 更新开发者文档Windows环境配置 (#2028)

.github/CONTRIBUTING_ENGLISH.md
- [✔️ ] 站点、文档改进
2028
| 🇨🇳 中文 |      windows环境下L7依赖安装英文文档修正    |
- [✅ ] 文档已补充或无须补充
- [✅  ] 代码演示已提供或无须提供
- [ ✅ ] TypeScript 定义已补充或无须补充
- [✅  ] Changelog 已提供或无须提供
---
=> docs: 更新开发者英文文档Windows环境配置（#2028）

.eslintrc.js, packages/core/src/services/shader/ShaderModuleService.ts
fix: 修复windows环境下shader字符串中的换行符导致shader替换结果错误的bug
---
=> fix: 修复windows环境下shader字符串中的换行符导致shader替换结果错误的bug

dev-demos/bugs/polygon/demos/highlight.tsx, dev-demos/bugs/polygon/highlight.md, packages/layers/src/core/BaseLayer.ts, packages/layers/src/line/models/great_circle.ts
=> fix: setdata 更新 & Arcline fix #2100

dev-demos/features/point/demos/circle-device.tsx, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/PixelPickingPlugin.ts, packages/renderer/src/device/DeviceModel.ts, packages/renderer/src/device/index.ts
使用 Device API 模式渲染下，开启 Blend 之后，拾取正常：
---
=> fix: blend in device api

dev-demos/features/point/demos/billboard.tsx, dev-demos/features/point/pointBillboard.md, packages/layers/src/point/models/billboard_point.ts, packages/layers/src/point/shaders/billboard_point_frag.glsl, packages/layers/src/point/shaders/billboard_point_vert.glsl
=> [wip]chore: update pointLayer billboard draw engine

dev-demos/features/geometry/demos/sprite.tsx, packages/layers/src/core/BaseLayer.ts, packages/layers/src/geometry/models/sprite.ts, packages/renderer/src/device/DeviceBuffer.ts, packages/renderer/src/device/DeviceModel.ts
让 Device API 渲染器支持 Sprite。
另外 Model 中的 updateAttribute 无需实现，Attribute 上本身就有更新 buffer 数据的方法：
```ts
attribute.updateBuffer({
data: [],
offset: 0,
});
```
例如在 Sprite model 中，不应该更新所有 attribute，只需要调用 position attribute 的更新即可：
```ts
// before
updateModel();
// after
const vertexAttribute =
this.styleAttributeService.getLayerStyleAttribute(
'position',
)?.vertexAttribute;
if (vertexAttribute) {
vertexAttribute.updateBuffer({
data: updated,
offset: 0,
});
}
```
---
=> feat: migrate sprite layer

dev-demos/features/mask/demos/singleMask.tsx, dev-demos/features/point/demos/circle-device.tsx, packages/core/src/services/layer/ILayerService.ts, packages/core/src/services/layer/LayerService.ts, packages/core/src/shaders/scene_uniforms.glsl, packages/layers/src/core/BaseLayer.ts, packages/layers/src/plugins/PixelPickingPlugin.ts, packages/layers/src/plugins/ShaderUniformPlugin.ts, packages/renderer/src/device/DeviceBuffer.ts, packages/renderer/src/device/DeviceModel.ts, packages/renderer/src/device/index.ts
目前多个图层无法单独拾取，原因是共用了一个全局 Picking Uniform Buffer。
每个 Layer 需要有自己单独的一个，但 Layer 中的多个 Model 可以共享。
另外 `u_Mvp` 这个高德地图下的 uniform 也应修改成 Layer 级而非全局，否则多个同类图层无法叠加。
---
=> fix: each layer should have its own picking ubo

dev-demos/webgpu/device/demos/texture.tsx, examples/demos/raster/dem.ts, examples/demos/raster/index.ts, examples/demos/raster/tiff.ts, examples/demos/webgpu/boids.ts, examples/demos/webgpu/compute_texture.ts, examples/demos/webgpu/index.ts, examples/demos/webgpu/template.ts, examples/demos/webgpu/texture.ts, examples/demos/webgpu/utils/common.ts, package.json, packages/layers/src/raster/models/raster.ts, packages/layers/src/raster/shaders/raster/raster_2d_frag.glsl, packages/renderer/package.json
=> Fix raster webgl1

packages/component/src/control/layerSwitch.ts
- ✅ 新特性提交
当multiple属性更新时，若此时layer显示的有多个，图层显隐控件需要把显示的图层控制为一个，其他图层都隐藏
修改前：从多选模式切换为单选模式，单选器选择多个
修改前：添加新图层，多选器选择了多个
修改后：更新layers 和 multiple 属性时，都处理的单选值，都仅显示一个图层
- ☑️ 文档已补充或无须补充
- ☑️ 代码演示已提供或无须提供
- ☑️ TypeScript 定义已补充或无须补充
- ☑️ Changelog 已提供或无须提供
---
=> feat: 图层显隐控件配置更新时，新增处理单选模式图层显示逻辑

.changeset/honest-poems-live.md, __tests__/integration/line.spec.ts, packages/maps/.fatherrc.ts, packages/maps/package.json
=> build: maps 包添加 umd 产物

CONTRIBUTING.en-US.md, CONTRIBUTING.md, README.en-US.md
=> docs: update tree structure

.changeset/late-plums-rule.md, packages/layers/__tests__/tile/raster-tile.spec.ts, packages/layers/src/core/BaseModel.ts, packages/layers/src/core/utils.ts
=> Fix regl bool uniform

packages/maps/src/amap-next/map.ts
高德因返回地图中心数据点，截取了前五位，精度丢失造成数据抖动
- [地图大于 20 级数据抖动背景及方案提议](https://www.yuque.com/antv/l7/dicwnx6mh1e2nc81#zchc2)
<table>
<tr>
<td>
before
<td>
now
<tr>
<td>
https://github.com/antvis/L7/assets/26923747/c548b083-4415-4906-8196-fe4467a69759
<td>
https://github.com/antvis/L7/assets/26923747/c68dffcd-8d48-4936-8395-84899eee8173
</table>
=> fix: 新版高德大于 21 级别抖动问题

examples/demos/components/index.ts, examples/demos/components/layerPopup.ts, packages/component/src/popup/layerPopup.ts
=> fix: 修复 LayerPopup followCursor 默认值问题

.changeset/tiny-seas-camp.md, examples/demos/bugfix/index.ts, examples/demos/bugfix/muti-polygon.ts, packages/layers/src/core/shape/extrude.ts, packages/layers/src/core/triangulation.ts, packages/layers/src/core/utils.ts, packages/utils/src/geo.ts
- fixed #2445
面图层使用 [earcut](https://github.com/mapbox/earcut) 算法进行三角剖分的时候，数据直接用的经纬度数据。
earcut 算法得是一个共平面的数据，也就是投影后的数据。
> Note that Earcut is a 2D triangulation algorithm, and handles 3D data as if it was projected onto the XY plane
将在进行三角剖分之前，将数据投影，获取正确索引数据，
<table>
<tr>
<td>
before
<td>
after
<tr>
<td>
<td>
<tr>
<td>
<td>
</table>
=> fix: mapbox 下部分面数据图层绘制异常

packages/renderer/src/device/DeviceTexture2D.ts
WebGL1 下需要使用 Format.F32_LUMINANCE
```ts
/**
* WebGL1 allow the combination of gl.LUMINANCE & gl.FLOAT with OES_texture_float
*/
format: queryVerdorInfo() === 'WebGL1' ? gl.LUMINANCE : gl.RED,
type: gl.FLOAT,
```
但其实这种组合是不符合规范的：
https://github.com/antvis/L7/pull/2128#issuecomment-1851922960
---
=> fix: raster with luminance in webgl1

.changeset/polite-apples-rule.md, packages/core/src/services/interaction/PickingService.ts, packages/core/src/services/renderer/passes/PixelPickingPass.ts, packages/renderer/src/device/index.ts
-  fixed #2504
readPixelsAsync 比 readPixels 慢，会造成拾取事件冒泡延迟，优先使用 readPixelsAsync，WebGPU 只支持 readPixelsAsync API
=> fix: 在 WebGL2 拾取事件冒泡延迟问题

packages/layers/src/line/shaders/arc3d/line_arc_3d_frag.glsl, packages/layers/src/line/shaders/greatCircle/line_arc_great_circle_frag.glsl, packages/layers/src/line/shaders/wall/wall_frag.glsl, packages/layers/src/line/shaders/wall/wall_vert.glsl
- #2525
顶点着色器与片元着色器 varying 变量顺序不一致问题
=> fix: WebGPU 渲染下着色器 varying 变量顺序不一致

.changeset/famous-geese-know.md, packages/renderer/src/device/DeviceModel.ts
- #2431
- #2525
在 WebGPU 下，每次 model draw 创建新 Pipeline，使用了缓存 createBindings，导致新的 Pipeline 使用 [getBindGroupLayout](https://developer.mozilla.org/en-US/docs/Web/API/GPUComputePipeline/getBindGroupLayout) 不一致。
因 L7 API 设计原因，draw 动态传入的参数（比如 stencil），必须每次创建 Pipeline，后续设计新 API 考虑 Pipeline 缓存情况。
=> fix: 修复 bindings 缓存在 WebGPU 的问题

site/docs/api/line_layer/style.en.md, site/docs/api/line_layer/style.zh.md
=> docs: 更新 LineLayer 图层下 style 中属性 dashArray 生效描述

.changeset/thick-wombats-lie.md, packages/core/src/services/source/ISourceService.ts, packages/source/src/parser/raster-tile.ts
瓦片图层不支持传入的 extent
rasterTile 支持 extent 与 coordinates 解析
---
=> feat: rasterTile support extent

.changeset/heavy-glasses-compete.md, packages/layers/src/plugins/FeatureScalePlugin.ts
=> fix: scale domain when default undefined

examples/demos/bugfix/index.ts, examples/demos/bugfix/simple-map.ts, package.json, packages/map/src/map/events.ts, packages/map/src/map/map.ts, packages/map/src/map/util/simpleMapCoord.ts, packages/maps/src/map/map.ts, site/docs/api/experiment/simple_coordinates.zh.md
fixed [#2721](https://github.com/antvis/L7/issues/2721) & [#2717](https://github.com/antvis/L7/issues/2717)
在event中，根据mapConfig的version和mapSize，重新计算lnglat。
| 🇺🇸 英文 |Fix MouseLocation in SIMPLE Map|
| 🇨🇳 中文 |鼠标坐标兼容简单坐标系|
---
=> Fix: simple map location
